package glfw

/*
#cgo CFLAGS: -DGLFW_INCLUDE_GLU
#cgo LDFLAGS: -lglfw
#include <GL/glfw3.h>
#include <stdlib.h>
*/
import "C"

const (
	// GLFW version
	VERSION_MAJOR    = C.GLFW_VERSION_MAJOR
	VERSION_MINOR    = C.GLFW_VERSION_MINOR
	VERSION_REVISION = C.GLFW_VERSION_REVISION

	// Input handling definitions

	// Key and button state/action definitions
	RELEASE = C.GLFW_RELEASE
	PRESS   = C.GLFW_PRESS

	// Keyboard raw key codes.
	// These key codes are inspired by the USB HID Usage Tables v1.12 (p. 53-60),
	// but re-arranged to map to 7-bit ASCII for printable keys (function keys are
	// put in the 256+ range).
	// The naming of the key codes follow these rules:
	//  - The US keyboard layout is used.
	//  - Names of printable alpha-numeric characters are used (e.g. "A", "R",
	//    "3", etc).
	//  - For non-alphanumeric characters, Unicode:ish names are used (e.g.
	//    "COMMA", "LEFT_SQUARE_BRACKET", etc). Note that some names do not
	//    correspond to the Unicode standard (usually for brevity).
	//  - Keys that lack a clear US mapping are named "WORLD_x".
	//  - For non-printable keys, custom names are used (e.g. "F4",
	//    "BACKSPACE", etc).

	// Printable keys
	KEY_SPACE         = C.GLFW_KEY_SPACE
	KEY_APOSTROPHE    = C.GLFW_KEY_APOSTROPHE
	KEY_COMMA         = C.GLFW_KEY_COMMA
	KEY_MINUS         = C.GLFW_KEY_MINUS
	KEY_PERIOD        = C.GLFW_KEY_PERIOD
	KEY_SLASH         = C.GLFW_KEY_SLASH
	KEY_0             = C.GLFW_KEY_0
	KEY_1             = C.GLFW_KEY_1
	KEY_2             = C.GLFW_KEY_2
	KEY_3             = C.GLFW_KEY_3
	KEY_4             = C.GLFW_KEY_4
	KEY_5             = C.GLFW_KEY_5
	KEY_6             = C.GLFW_KEY_6
	KEY_7             = C.GLFW_KEY_7
	KEY_8             = C.GLFW_KEY_8
	KEY_9             = C.GLFW_KEY_9
	KEY_SEMICOLON     = C.GLFW_KEY_SEMICOLON
	KEY_EQUAL         = C.GLFW_KEY_EQUAL
	KEY_A             = C.GLFW_KEY_A
	KEY_B             = C.GLFW_KEY_B
	KEY_C             = C.GLFW_KEY_C
	KEY_D             = C.GLFW_KEY_D
	KEY_E             = C.GLFW_KEY_E
	KEY_F             = C.GLFW_KEY_F
	KEY_G             = C.GLFW_KEY_G
	KEY_H             = C.GLFW_KEY_H
	KEY_I             = C.GLFW_KEY_I
	KEY_J             = C.GLFW_KEY_J
	KEY_K             = C.GLFW_KEY_K
	KEY_L             = C.GLFW_KEY_L
	KEY_M             = C.GLFW_KEY_M
	KEY_N             = C.GLFW_KEY_N
	KEY_O             = C.GLFW_KEY_O
	KEY_P             = C.GLFW_KEY_P
	KEY_Q             = C.GLFW_KEY_Q
	KEY_R             = C.GLFW_KEY_R
	KEY_S             = C.GLFW_KEY_S
	KEY_T             = C.GLFW_KEY_T
	KEY_U             = C.GLFW_KEY_U
	KEY_V             = C.GLFW_KEY_V
	KEY_W             = C.GLFW_KEY_W
	KEY_X             = C.GLFW_KEY_X
	KEY_Y             = C.GLFW_KEY_Y
	KEY_Z             = C.GLFW_KEY_Z
	KEY_LEFT_BRACKET  = C.GLFW_KEY_LEFT_BRACKET
	KEY_BACKSLASH     = C.GLFW_KEY_BACKSLASH
	KEY_RIGHT_BRACKET = C.GLFW_KEY_RIGHT_BRACKET
	KEY_GRAVE_ACCENT  = C.GLFW_KEY_GRAVE_ACCENT
	KEY_WORLD_1       = C.GLFW_KEY_WORLD_1
	KEY_WORLD_2       = C.GLFW_KEY_WORLD_2

	// Function keys
	KEY_ESCAPE        = C.GLFW_KEY_ESCAPE
	KEY_ENTER         = C.GLFW_KEY_ENTER
	KEY_TAB           = C.GLFW_KEY_TAB
	KEY_BACKSPACE     = C.GLFW_KEY_BACKSPACE
	KEY_INSERT        = C.GLFW_KEY_INSERT
	KEY_DELETE        = C.GLFW_KEY_DELETE
	KEY_RIGHT         = C.GLFW_KEY_RIGHT
	KEY_LEFT          = C.GLFW_KEY_LEFT
	KEY_DOWN          = C.GLFW_KEY_DOWN
	KEY_UP            = C.GLFW_KEY_UP
	KEY_PAGE_UP       = C.GLFW_KEY_PAGE_UP
	KEY_PAGE_DOWN     = C.GLFW_KEY_PAGE_DOWN
	KEY_HOME          = C.GLFW_KEY_HOME
	KEY_END           = C.GLFW_KEY_END
	KEY_CAPS_LOCK     = C.GLFW_KEY_CAPS_LOCK
	KEY_SCROLL_LOCK   = C.GLFW_KEY_SCROLL_LOCK
	KEY_NUM_LOCK      = C.GLFW_KEY_NUM_LOCK
	KEY_PRINT_SCREEN  = C.GLFW_KEY_PRINT_SCREEN
	KEY_PAUSE         = C.GLFW_KEY_PAUSE
	KEY_F1            = C.GLFW_KEY_F1
	KEY_F2            = C.GLFW_KEY_F2
	KEY_F3            = C.GLFW_KEY_F3
	KEY_F4            = C.GLFW_KEY_F4
	KEY_F5            = C.GLFW_KEY_F5
	KEY_F6            = C.GLFW_KEY_F6
	KEY_F7            = C.GLFW_KEY_F7
	KEY_F8            = C.GLFW_KEY_F8
	KEY_F9            = C.GLFW_KEY_F9
	KEY_F10           = C.GLFW_KEY_F10
	KEY_F11           = C.GLFW_KEY_F11
	KEY_F12           = C.GLFW_KEY_F12
	KEY_F13           = C.GLFW_KEY_F13
	KEY_F14           = C.GLFW_KEY_F14
	KEY_F15           = C.GLFW_KEY_F15
	KEY_F16           = C.GLFW_KEY_F16
	KEY_F17           = C.GLFW_KEY_F17
	KEY_F18           = C.GLFW_KEY_F18
	KEY_F19           = C.GLFW_KEY_F19
	KEY_F20           = C.GLFW_KEY_F20
	KEY_F21           = C.GLFW_KEY_F21
	KEY_F22           = C.GLFW_KEY_F22
	KEY_F23           = C.GLFW_KEY_F23
	KEY_F24           = C.GLFW_KEY_F24
	KEY_F25           = C.GLFW_KEY_F25
	KEY_KP_0          = C.GLFW_KEY_KP_0
	KEY_KP_1          = C.GLFW_KEY_KP_1
	KEY_KP_2          = C.GLFW_KEY_KP_2
	KEY_KP_3          = C.GLFW_KEY_KP_3
	KEY_KP_4          = C.GLFW_KEY_KP_4
	KEY_KP_5          = C.GLFW_KEY_KP_5
	KEY_KP_6          = C.GLFW_KEY_KP_6
	KEY_KP_7          = C.GLFW_KEY_KP_7
	KEY_KP_8          = C.GLFW_KEY_KP_8
	KEY_KP_9          = C.GLFW_KEY_KP_9
	KEY_KP_DECIMAL    = C.GLFW_KEY_KP_DECIMAL
	KEY_KP_DIVIDE     = C.GLFW_KEY_KP_DIVIDE
	KEY_KP_MULTIPLY   = C.GLFW_KEY_KP_MULTIPLY
	KEY_KP_SUBTRACT   = C.GLFW_KEY_KP_SUBTRACT
	KEY_KP_ADD        = C.GLFW_KEY_KP_ADD
	KEY_KP_ENTER      = C.GLFW_KEY_KP_ENTER
	KEY_KP_EQUAL      = C.GLFW_KEY_KP_EQUAL
	KEY_LEFT_SHIFT    = C.GLFW_KEY_LEFT_SHIFT
	KEY_LEFT_CONTROL  = C.GLFW_KEY_LEFT_CONTROL
	KEY_LEFT_ALT      = C.GLFW_KEY_LEFT_ALT
	KEY_LEFT_SUPER    = C.GLFW_KEY_LEFT_SUPER
	KEY_RIGHT_SHIFT   = C.GLFW_KEY_RIGHT_SHIFT
	KEY_RIGHT_CONTROL = C.GLFW_KEY_RIGHT_CONTROL
	KEY_RIGHT_ALT     = C.GLFW_KEY_RIGHT_ALT
	KEY_RIGHT_SUPER   = C.GLFW_KEY_RIGHT_SUPER
	KEY_MENU          = C.GLFW_KEY_MENU
	KEY_LAST          = C.GLFW_KEY_LAST

	// GLFW 2.x key name aliases (deprecated)
	KEY_ESC         = C.GLFW_KEY_ESC
	KEY_DEL         = C.GLFW_KEY_DEL
	KEY_PAGEUP      = C.GLFW_KEY_PAGEUP
	KEY_PAGEDOWN    = C.GLFW_KEY_PAGEDOWN
	KEY_KP_NUM_LOCK = C.GLFW_KEY_KP_NUM_LOCK
	KEY_LCTRL       = C.GLFW_KEY_LCTRL
	KEY_LSHIFT      = C.GLFW_KEY_LSHIFT
	KEY_LALT        = C.GLFW_KEY_LALT
	KEY_LSUPER      = C.GLFW_KEY_LSUPER
	KEY_RCTRL       = C.GLFW_KEY_RCTRL
	KEY_RSHIFT      = C.GLFW_KEY_RSHIFT
	KEY_RALT        = C.GLFW_KEY_RALT
	KEY_RSUPER      = C.GLFW_KEY_RSUPER

	// Mouse button definitions
	MOUSE_BUTTON_1    = C.GLFW_MOUSE_BUTTON_1
	MOUSE_BUTTON_2    = C.GLFW_MOUSE_BUTTON_2
	MOUSE_BUTTON_3    = C.GLFW_MOUSE_BUTTON_3
	MOUSE_BUTTON_4    = C.GLFW_MOUSE_BUTTON_4
	MOUSE_BUTTON_5    = C.GLFW_MOUSE_BUTTON_5
	MOUSE_BUTTON_6    = C.GLFW_MOUSE_BUTTON_6
	MOUSE_BUTTON_7    = C.GLFW_MOUSE_BUTTON_7
	MOUSE_BUTTON_8    = C.GLFW_MOUSE_BUTTON_8
	MOUSE_BUTTON_LAST = C.GLFW_MOUSE_BUTTON_LAST

	// Mouse button aliases
	MOUSE_BUTTON_LEFT   = C.GLFW_MOUSE_BUTTON_LEFT
	MOUSE_BUTTON_RIGHT  = C.GLFW_MOUSE_BUTTON_RIGHT
	MOUSE_BUTTON_MIDDLE = C.GLFW_MOUSE_BUTTON_MIDDLE

	// Joystick identifiers
	JOYSTICK_1    = C.GLFW_JOYSTICK_1
	JOYSTICK_2    = C.GLFW_JOYSTICK_2
	JOYSTICK_3    = C.GLFW_JOYSTICK_3
	JOYSTICK_4    = C.GLFW_JOYSTICK_4
	JOYSTICK_5    = C.GLFW_JOYSTICK_5
	JOYSTICK_6    = C.GLFW_JOYSTICK_6
	JOYSTICK_7    = C.GLFW_JOYSTICK_7
	JOYSTICK_8    = C.GLFW_JOYSTICK_8
	JOYSTICK_9    = C.GLFW_JOYSTICK_9
	JOYSTICK_10   = C.GLFW_JOYSTICK_10
	JOYSTICK_11   = C.GLFW_JOYSTICK_11
	JOYSTICK_12   = C.GLFW_JOYSTICK_12
	JOYSTICK_13   = C.GLFW_JOYSTICK_13
	JOYSTICK_14   = C.GLFW_JOYSTICK_14
	JOYSTICK_15   = C.GLFW_JOYSTICK_15
	JOYSTICK_16   = C.GLFW_JOYSTICK_16
	JOYSTICK_LAST = C.GLFW_JOYSTICK_LAST

	// Other definitions

	// glfwCreateWindow modes
	WINDOWED   = C.GLFW_WINDOWED
	FULLSCREEN = C.GLFW_FULLSCREEN

	// glfwGetWindowParam tokens
	ACTIVE          = C.GLFW_ACTIVE
	ICONIFIED       = C.GLFW_ICONIFIED
	CLOSE_REQUESTED = C.GLFW_CLOSE_REQUESTED
	OPENGL_REVISION = C.GLFW_OPENGL_REVISION

	// glfwWindowH = C.tokens
	RED_BITS         = C.GLFW_RED_BITS
	GREEN_BITS       = C.GLFW_GREEN_BITS
	BLUE_BITS        = C.GLFW_BLUE_BITS
	ALPHA_BITS       = C.GLFW_ALPHA_BITS
	DEPTH_BITS       = C.GLFW_DEPTH_BITS
	STENCIL_BITS     = C.GLFW_STENCIL_BITS
	REFRESH_RATE     = C.GLFW_REFRESH_RATE
	ACCUM_RED_BITS   = C.GLFW_ACCUM_RED_BITS
	ACCUM_GREEN_BITS = C.GLFW_ACCUM_GREEN_BITS
	ACCUM_BLUE_BITS  = C.GLFW_ACCUM_BLUE_BITS
	ACCUM_ALPHA_BITS = C.GLFW_ACCUM_ALPHA_BITS
	AUX_BUFFERS      = C.GLFW_AUX_BUFFERS
	STEREO           = C.GLFW_STEREO
	FSAA_SAMPLES     = C.GLFW_FSAA_SAMPLES

	// The following constants are used with both glfwGetWindowParam
	// and glfwWindowHint

	OPENGL_VERSION_MAJOR  = C.GLFW_OPENGL_VERSION_MAJOR
	OPENGL_VERSION_MINOR  = C.GLFW_OPENGL_VERSION_MINOR
	OPENGL_FORWARD_COMPAT = C.GLFW_OPENGL_FORWARD_COMPAT
	OPENGL_DEBUG_CONTEXT  = C.GLFW_OPENGL_DEBUG_CONTEXT
	OPENGL_PROFILE        = C.GLFW_OPENGL_PROFILE
	OPENGL_ROBUSTNESS     = C.GLFW_OPENGL_ROBUSTNESS
	RESIZABLE             = C.GLFW_RESIZABLE
	VISIBLE               = C.GLFW_VISIBLE

	// GLFW_OPENGL_ROBUSTNESS mode tokens
	OPENGL_NO_ROBUSTNESS         = C.GLFW_OPENGL_NO_ROBUSTNESS
	OPENGL_NO_RESET_NOTIFICATION = C.GLFW_OPENGL_NO_RESET_NOTIFICATION
	OPENGL_LOSE_CONTEXT_ON_RESET = C.GLFW_OPENGL_LOSE_CONTEXT_ON_RESET

	// GLFW_OPENGL_PROFILE bit tokens
	OPENGL_NO_PROFILE     = C.GLFW_OPENGL_NO_PROFILE
	OPENGL_CORE_PROFILE   = C.GLFW_OPENGL_CORE_PROFILE
	OPENGL_COMPAT_PROFILE = C.GLFW_OPENGL_COMPAT_PROFILE
	OPENGL_ES2_PROFILE    = C.GLFW_OPENGL_ES2_PROFILE

	// glfwGetInputMode/glfwSetInputMode tokens
	CURSOR_MODE          = C.GLFW_CURSOR_MODE
	STICKY_KEYS          = C.GLFW_STICKY_KEYS
	STICKY_MOUSE_BUTTONS = C.GLFW_STICKY_MOUSE_BUTTONS
	SYSTEM_KEYS          = C.GLFW_SYSTEM_KEYS
	KEY_REPEAT           = C.GLFW_KEY_REPEAT

	// GLFW_CURSOR_MODE values
	CURSOR_NORMAL   = C.GLFW_CURSOR_NORMAL
	CURSOR_HIDDEN   = C.GLFW_CURSOR_HIDDEN
	CURSOR_CAPTURED = C.GLFW_CURSOR_CAPTURED

	// glfwGetJoystickParam tokens
	PRESENT = C.GLFW_PRESENT
	AXES    = C.GLFW_AXES
	BUTTONS = C.GLFW_BUTTONS

	// glfwGetError/glfwErrorString tokens
	NO_ERROR            = C.GLFW_NO_ERROR
	NOT_INITIALIZED     = C.GLFW_NOT_INITIALIZED
	NO_CURRENT_CONTEXT  = C.GLFW_NO_CURRENT_CONTEXT
	INVALID_ENUM        = C.GLFW_INVALID_ENUM
	INVALID_VALUE       = C.GLFW_INVALID_VALUE
	OUT_OF_MEMORY       = C.GLFW_OUT_OF_MEMORY
	OPENGL_UNAVAILABLE  = C.GLFW_OPENGL_UNAVAILABLE
	VERSION_UNAVAILABLE = C.GLFW_VERSION_UNAVAILABLE
	PLATFORM_ERROR      = C.GLFW_PLATFORM_ERROR
	WINDOW_NOT_ACTIVE   = C.GLFW_WINDOW_NOT_ACTIVE
	FORMAT_UNAVAILABLE  = C.GLFW_FORMAT_UNAVAILABLE

	// Gamma ramps
	GAMMA_RAMP_SIZE = C.GLFW_GAMMA_RAMP_SIZE
)

