// Copyright 2012 Lightpoke. All rights reserved.
// This source code is subject to the terms and
// conditions defined in the "License.txt" file.
//
// Code generated by this program is also under
// the above license.

package generator

import (
	"fmt"
)

func init() {
	specialProcedures["glAreTexturesResident"] = func(ctx, prefix string, p *Procedure) (name, args, body, returns string) {
		body = fmt.Sprintf(`
	var cRes *C.GLboolean
	status = C.%sAreTexturesResident(%s, C.GLsizei(len(textures)), (*C.GLuint)(unsafe.Pointer(&textures[0])), cRes) != 0

	residencies = make([]bool, len(textures))
	for i := 0; i < len(textures); i++ {
		residencies[i] = (*(*C.GLboolean)(unsafe.Pointer(uintptr(unsafe.Pointer(cRes)) + uintptr(i)))) != 0
	}
	return
`, prefix, ctx)

		return "AreTexturesResident", "textures []uint32", body, "(status bool, residencies []bool)"
	}
}
