// Copyright 2012 Lightpoke. All rights reserved.
// This source code is subject to the terms and
// conditions defined in the "License.txt" file.
//
// Code generated by this program is also under
// the above license.

package generator

import (
	"fmt"
)

func init() {
	specialProcedures["glBindAttribLocation"] = func(ctx, prefix string, p *Procedure) (name, args, untypedArgs, body, returns string) {
		body = fmt.Sprintf(`
	cstr := C.CString(name)
	defer C.free(unsafe.Pointer(&cstr))

	C.%sBindAttribLocation(%s, C.GLuint(program), C.GLuint(index), (*C.GLchar)(unsafe.Pointer(cstr)))
	return
`, prefix, ctx)

		name = "BindAttribLocation"
		args = "program, index uint32, name string"
		untypedArgs = "program, index, name"
		returns = ""
		return
	}
}
