// Copyright 2012 Lightpoke. All rights reserved.
// This source code is subject to the terms and
// conditions defined in the "License.txt" file.
//
// Code generated by this program is also under
// the above license.

package generator

import (
	"fmt"
)

func init() {
	specialProcedures["glEnd"] = func(ctx, prefix string, p *Procedure) (name, args, body, returns string) {
		body = fmt.Sprintf(`

	C.%sEnd(%s)
	glc.inBeginEnd = false
	return
`, prefix, ctx)

		return "End", "", body, ""
	}
}
