// Copyright 2012 Lightpoke. All rights reserved.
// This source code is subject to the terms and
// conditions defined in the "License.txt" file.
//
// Code generated by this program is also under
// the above license.

package generator

import (
	"fmt"
)

func init() {
	specialProcedures["glGetString"] = func(ctx, prefix string, p *Procedure) (name, args, body, returns string) {
		body = fmt.Sprintf(`
	cstr := C.%sGetString(%s, C.GLenum(name))
	return C.GoString((*C.char)(unsafe.Pointer(cstr)))
`, prefix, ctx)

		return "GetString", "name uint32", body, "string"
	}
}
