#include <stdbool.h>
#include <stdlib.h>

typedef char GLchar;
typedef unsigned int GLenum;
typedef unsigned char GLboolean;
typedef unsigned int GLbitfield;
typedef signed char GLbyte;
typedef short GLshort;
typedef int GLint;
typedef int GLsizei;
typedef unsigned char GLubyte;
typedef unsigned short GLushort;
typedef unsigned int GLuint;
typedef float GLfloat;
typedef float GLclampf;
typedef double GLdouble;
typedef double GLclampd;
typedef void GLvoid;
typedef ptrdiff_t GLsizeiptr;
typedef ptrdiff_t GLintptr;

typedef void(*gl21PAccum)(GLenum, GLfloat);
typedef void(*gl21PAlphaFunc)(GLenum, GLclampf);
typedef void(*gl21PBegin)(GLenum);
typedef void(*gl21PEnd)();
typedef void(*gl21PBitmap)(GLsizei, GLsizei, GLfloat, GLfloat, GLfloat, GLfloat, GLubyte*);
typedef void(*gl21PBlendFunc)(GLenum, GLenum);
typedef void(*gl21PCallList)(GLuint);
typedef void(*gl21PCallLists)(GLsizei, GLenum, GLvoid*);
typedef void(*gl21PClear)(GLbitfield);
typedef void(*gl21PClearAccum)(GLfloat, GLfloat, GLfloat, GLfloat);
typedef void(*gl21PClearColor)(GLclampf, GLclampf, GLclampf, GLclampf);
typedef void(*gl21PClearDepth)(GLclampd);
typedef void(*gl21PClearIndex)(GLfloat);
typedef void(*gl21PClearStencil)(GLint);
typedef void(*gl21PClipPlane)(GLenum, GLdouble*);
typedef void(*gl21PColor3b)(GLbyte, GLbyte, GLbyte);
typedef void(*gl21PColor3d)(GLdouble, GLdouble, GLdouble);
typedef void(*gl21PColor3f)(GLfloat, GLfloat, GLfloat);
typedef void(*gl21PColor3i)(GLint, GLint, GLint);
typedef void(*gl21PColor3s)(GLshort, GLshort, GLshort);
typedef void(*gl21PColor3ub)(GLubyte, GLubyte, GLubyte);
typedef void(*gl21PColor3ui)(GLuint, GLuint, GLuint);
typedef void(*gl21PColor3us)(GLushort, GLushort, GLushort);
typedef void(*gl21PColor4b)(GLbyte, GLbyte, GLbyte, GLbyte);
typedef void(*gl21PColor4d)(GLdouble, GLdouble, GLdouble, GLdouble);
typedef void(*gl21PColor4f)(GLfloat, GLfloat, GLfloat, GLfloat);
typedef void(*gl21PColor4i)(GLint, GLint, GLint, GLint);
typedef void(*gl21PColor4s)(GLshort, GLshort, GLshort, GLshort);
typedef void(*gl21PColor4ub)(GLubyte, GLubyte, GLubyte, GLubyte);
typedef void(*gl21PColor4ui)(GLuint, GLuint, GLuint, GLuint);
typedef void(*gl21PColor4us)(GLushort, GLushort, GLushort, GLushort);
typedef void(*gl21PColor3bv)(GLbyte*);
typedef void(*gl21PColor3dv)(GLdouble*);
typedef void(*gl21PColor3fv)(GLfloat*);
typedef void(*gl21PColor3iv)(GLint*);
typedef void(*gl21PColor3sv)(GLshort*);
typedef void(*gl21PColor3ubv)(GLubyte*);
typedef void(*gl21PColor3uiv)(GLuint*);
typedef void(*gl21PColor3usv)(GLushort*);
typedef void(*gl21PColor4bv)(GLbyte*);
typedef void(*gl21PColor4dv)(GLdouble*);
typedef void(*gl21PColor4fv)(GLfloat*);
typedef void(*gl21PColor4iv)(GLint*);
typedef void(*gl21PColor4sv)(GLshort*);
typedef void(*gl21PColor4ubv)(GLubyte*);
typedef void(*gl21PColor4uiv)(GLuint*);
typedef void(*gl21PColor4usv)(GLushort*);
typedef void(*gl21PColorMask)(GLboolean, GLboolean, GLboolean, GLboolean);
typedef void(*gl21PColorMaterial)(GLenum, GLenum);
typedef void(*gl21PCopyPixels)(GLint, GLint, GLsizei, GLsizei, GLenum);
typedef void(*gl21PCullFace)(GLenum);
typedef void(*gl21PDeleteLists)(GLuint, GLsizei);
typedef void(*gl21PDepthFunc)(GLenum);
typedef void(*gl21PDepthMask)(GLboolean);
typedef void(*gl21PDepthRange)(GLclampd, GLclampd);
typedef void(*gl21PEnable)(GLenum);
typedef void(*gl21PDisable)(GLenum);
typedef void(*gl21PDrawBuffer)(GLenum);
typedef void(*gl21PDrawPixels)(GLsizei, GLsizei, GLenum, GLenum, GLvoid*);
typedef void(*gl21PEdgeFlag)(GLboolean);
typedef void(*gl21PEdgeFlagv)(GLboolean*);
typedef void(*gl21PEdgeFlagPointer)(GLsizei, GLvoid*);
typedef void(*gl21PEvalCoord1d)(GLdouble);
typedef void(*gl21PEvalCoord1f)(GLfloat);
typedef void(*gl21PEvalCoord2d)(GLdouble, GLdouble);
typedef void(*gl21PEvalCoord2f)(GLfloat, GLfloat);
typedef void(*gl21PEvalCoord1dv)(GLdouble*);
typedef void(*gl21PEvalCoord1fv)(GLfloat*);
typedef void(*gl21PEvalCoord2dv)(GLdouble*);
typedef void(*gl21PEvalCoord2fv)(GLfloat*);
typedef void(*gl21PEvalMesh1)(GLenum, GLint, GLint);
typedef void(*gl21PEvalMesh2)(GLenum, GLint, GLint, GLint, GLint);
typedef void(*gl21PEvalPoint1)(GLint);
typedef void(*gl21PEvalPoint2)(GLint, GLint);
typedef void(*gl21PFeedbackBuffer)(GLsizei, GLenum, GLfloat*);
typedef void(*gl21PFinish)();
typedef void(*gl21PFlush)();
typedef void(*gl21PFogf)(GLenum, GLfloat);
typedef void(*gl21PFogi)(GLenum, GLint);
typedef void(*gl21PFogfv)(GLenum, GLfloat*);
typedef void(*gl21PFogiv)(GLenum, GLint*);
typedef void(*gl21PFrontFace)(GLenum);
typedef void(*gl21PFrustum)(GLdouble, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble);
typedef GLuint(*gl21PGenLists)(GLsizei);
typedef void(*gl21PGetBooleanv)(GLenum, GLboolean*);
typedef void(*gl21PGetDoublev)(GLenum, GLdouble*);
typedef void(*gl21PGetFloatv)(GLenum, GLfloat*);
typedef void(*gl21PGetIntegerv)(GLenum, GLint*);
typedef void(*gl21PGetClipPlane)(GLenum, GLdouble*);
typedef GLenum(*gl21PGetError)();
typedef void(*gl21PGetLightfv)(GLenum, GLenum, GLfloat*);
typedef void(*gl21PGetLightiv)(GLenum, GLenum, GLint*);
typedef void(*gl21PGetMapdv)(GLenum, GLenum, GLdouble*);
typedef void(*gl21PGetMapfv)(GLenum, GLenum, GLfloat*);
typedef void(*gl21PGetMapiv)(GLenum, GLenum, GLint*);
typedef void(*gl21PGetMaterialfv)(GLenum, GLenum, GLfloat*);
typedef void(*gl21PGetMaterialiv)(GLenum, GLenum, GLint*);
typedef void(*gl21PGetPixelMapfv)(GLenum, GLfloat*);
typedef void(*gl21PGetPixelMapuiv)(GLenum, GLuint*);
typedef void(*gl21PGetPixelMapusv)(GLenum, GLushort*);
typedef void(*gl21PGetPolygonStipple)(GLubyte*);
typedef GLubyte*(*gl21PGetString)(GLenum);
typedef void(*gl21PGetTexEnvfv)(GLenum, GLenum, GLfloat*);
typedef void(*gl21PGetTexEnviv)(GLenum, GLenum, GLint*);
typedef void(*gl21PGetTexGendv)(GLenum, GLenum, GLdouble*);
typedef void(*gl21PGetTexGenfv)(GLenum, GLenum, GLfloat*);
typedef void(*gl21PGetTexGeniv)(GLenum, GLenum, GLint*);
typedef void(*gl21PGetTexImage)(GLenum, GLint, GLenum, GLenum, GLvoid*);
typedef void(*gl21PGetTexLevelParameterfv)(GLenum, GLint, GLenum, GLfloat*);
typedef void(*gl21PGetTexLevelParameteriv)(GLenum, GLint, GLenum, GLint*);
typedef void(*gl21PGetTexParameterfv)(GLenum, GLenum, GLfloat*);
typedef void(*gl21PGetTexParameteriv)(GLenum, GLenum, GLint*);
typedef void(*gl21PHint)(GLenum, GLenum);
typedef void(*gl21PIndexd)(GLdouble);
typedef void(*gl21PIndexf)(GLfloat);
typedef void(*gl21PIndexi)(GLint);
typedef void(*gl21PIndexs)(GLshort);
typedef void(*gl21PIndexdv)(GLdouble*);
typedef void(*gl21PIndexfv)(GLfloat*);
typedef void(*gl21PIndexiv)(GLint*);
typedef void(*gl21PIndexsv)(GLshort*);
typedef void(*gl21PIndexMask)(GLuint);
typedef void(*gl21PIndexPointer)(GLenum, GLsizei, GLvoid*);
typedef void(*gl21PInitNames)();
typedef void(*gl21PIsEnabled)(GLenum);
typedef GLboolean(*gl21PIsList)(GLuint);
typedef void(*gl21PLightf)(GLenum, GLenum, GLfloat);
typedef void(*gl21PLighti)(GLenum, GLenum, GLint);
typedef void(*gl21PLightfv)(GLenum, GLenum, GLfloat*);
typedef void(*gl21PLightiv)(GLenum, GLenum, GLint*);
typedef void(*gl21PLightModelf)(GLenum, GLfloat);
typedef void(*gl21PLightModeli)(GLenum, GLint);
typedef void(*gl21PLightModelfv)(GLenum, GLfloat*);
typedef void(*gl21PLightModeliv)(GLenum, GLint*);
typedef void(*gl21PLineStipple)(GLint, GLushort);
typedef void(*gl21PLineWidth)(GLfloat);
typedef void(*gl21PListBase)(GLuint);
typedef void(*gl21PLoadIdentity)();
typedef void(*gl21PLoadMatrixd)(GLdouble*);
typedef void(*gl21PLoadMatrixf)(GLfloat*);
typedef void(*gl21PLoadName)(GLuint);
typedef void(*gl21PLogicOp)(GLenum);
typedef void(*gl21PMap1d)(GLenum, GLdouble, GLdouble, GLint, GLint, GLdouble*);
typedef void(*gl21PMap1f)(GLenum, GLfloat, GLfloat, GLint, GLint, GLfloat*);
typedef void(*gl21PMap2d)(GLenum, GLdouble, GLdouble, GLint, GLint, GLdouble, GLdouble, GLint, GLint, GLdouble*);
typedef void(*gl21PMap2f)(GLenum, GLfloat, GLfloat, GLint, GLint, GLfloat, GLfloat, GLint, GLint, GLfloat*);
typedef void(*gl21PMapGrid1d)(GLint, GLdouble, GLdouble);
typedef void(*gl21PMapGrid1f)(GLint, GLfloat, GLfloat);
typedef void(*gl21PMapGrid2d)(GLint, GLdouble, GLdouble, GLint, GLdouble, GLdouble);
typedef void(*gl21PMapGrid2f)(GLint, GLfloat, GLfloat, GLint, GLfloat, GLfloat);
typedef void(*gl21PMaterialf)(GLenum, GLenum, GLfloat);
typedef void(*gl21PMateriali)(GLenum, GLenum, GLint);
typedef void(*gl21PMaterialfv)(GLenum, GLenum, GLfloat*);
typedef void(*gl21PMaterialiv)(GLenum, GLenum, GLint*);
typedef void(*gl21PMatrixMode)(GLenum);
typedef void(*gl21PMultMatrixd)(GLdouble*);
typedef void(*gl21PMultMatrixf)(GLfloat*);
typedef void(*gl21PNewList)(GLuint, GLenum);
typedef void(*gl21PEndList)();
typedef void(*gl21PNormal3b)(GLbyte, GLbyte, GLbyte);
typedef void(*gl21PNormal3d)(GLdouble, GLdouble, GLdouble);
typedef void(*gl21PNormal3f)(GLfloat, GLfloat, GLfloat);
typedef void(*gl21PNormal3i)(GLint, GLint, GLint);
typedef void(*gl21PNormal3s)(GLshort, GLshort, GLshort);
typedef void(*gl21PNormal3bv)(GLbyte*);
typedef void(*gl21PNormal3dv)(GLdouble*);
typedef void(*gl21PNormal3fv)(GLfloat*);
typedef void(*gl21PNormal3iv)(GLint*);
typedef void(*gl21PNormal3sv)(GLshort*);
typedef void(*gl21POrtho)(GLdouble, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble);
typedef void(*gl21PPassThrough)(GLfloat);
typedef void(*gl21PPixelMapfv)(GLenum, GLsizei, GLfloat*);
typedef void(*gl21PPixelMapuiv)(GLenum, GLsizei, GLuint*);
typedef void(*gl21PPixelMapusv)(GLenum, GLsizei, GLushort*);
typedef void(*gl21PPixelStoref)(GLenum, GLfloat);
typedef void(*gl21PPixelStorei)(GLenum, GLint);
typedef void(*gl21PPixelTransferf)(GLenum, GLfloat);
typedef void(*gl21PPixelTransferi)(GLenum, GLint);
typedef void(*gl21PPixelZoom)(GLfloat, GLfloat);
typedef void(*gl21PPointSize)(GLfloat);
typedef void(*gl21PPolygonMode)(GLenum, GLenum);
typedef void(*gl21PPolygonStipple)(GLubyte*);
typedef void(*gl21PPushAttrib)(GLbitfield);
typedef void(*gl21PPopAttrib)();
typedef void(*gl21PPushMatrix)();
typedef void(*gl21PPopMatrix)();
typedef void(*gl21PPushName)(GLuint);
typedef void(*gl21PPopName)();
typedef void(*gl21PRasterPos2d)(GLdouble, GLdouble);
typedef void(*gl21PRasterPos2f)(GLfloat, GLfloat);
typedef void(*gl21PRasterPos2i)(GLint, GLint);
typedef void(*gl21PRasterPos2s)(GLshort, GLshort);
typedef void(*gl21PRasterPos3d)(GLdouble, GLdouble, GLdouble);
typedef void(*gl21PRasterPos3f)(GLfloat, GLfloat, GLfloat);
typedef void(*gl21PRasterPos3i)(GLint, GLint, GLint);
typedef void(*gl21PRasterPos3s)(GLshort, GLshort, GLshort);
typedef void(*gl21PRasterPos4d)(GLdouble, GLdouble, GLdouble, GLdouble);
typedef void(*gl21PRasterPos4f)(GLfloat, GLfloat, GLfloat, GLfloat);
typedef void(*gl21PRasterPos4i)(GLint, GLint, GLint, GLint);
typedef void(*gl21PRasterPos4s)(GLshort, GLshort, GLshort, GLshort);
typedef void(*gl21PRasterPos2dv)(GLdouble*);
typedef void(*gl21PRasterPos2fv)(GLfloat*);
typedef void(*gl21PRasterPos2iv)(GLint*);
typedef void(*gl21PRasterPos2sv)(GLshort*);
typedef void(*gl21PRasterPos3dv)(GLdouble*);
typedef void(*gl21PRasterPos3fv)(GLfloat*);
typedef void(*gl21PRasterPos3iv)(GLint*);
typedef void(*gl21PRasterPos3sv)(GLshort*);
typedef void(*gl21PRasterPos4dv)(GLdouble*);
typedef void(*gl21PRasterPos4fv)(GLfloat*);
typedef void(*gl21PRasterPos4iv)(GLint*);
typedef void(*gl21PRasterPos4sv)(GLshort*);
typedef void(*gl21PReadBuffer)(GLenum);
typedef void(*gl21PReadPixels)(GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, GLvoid*);
typedef void(*gl21PRectd)(GLdouble, GLdouble, GLdouble, GLdouble);
typedef void(*gl21PRectf)(GLfloat, GLfloat, GLfloat, GLfloat);
typedef void(*gl21PRecti)(GLint, GLint, GLint, GLint);
typedef void(*gl21PRects)(GLshort, GLshort, GLshort, GLshort);
typedef void(*gl21PRectdv)(GLdouble*, GLdouble*);
typedef void(*gl21PRectfv)(GLfloat*, GLfloat*);
typedef void(*gl21PRectiv)(GLint*, GLint*);
typedef void(*gl21PRectsv)(GLshort*, GLshort*);
typedef GLint(*gl21PRenderMode)(GLenum);
typedef void(*gl21PRotated)(GLdouble, GLdouble, GLdouble, GLdouble);
typedef void(*gl21PRotatef)(GLfloat, GLfloat, GLfloat, GLfloat);
typedef void(*gl21PScaled)(GLdouble, GLdouble, GLdouble);
typedef void(*gl21PScalef)(GLfloat, GLfloat, GLfloat);
typedef void(*gl21PScissor)(GLint, GLint, GLsizei, GLsizei);
typedef void(*gl21PSelectBuffer)(GLsizei, GLuint*);
typedef void(*gl21PShadeModel)(GLenum);
typedef void(*gl21PStencilFunc)(GLenum, GLint, GLuint);
typedef void(*gl21PStencilMask)(GLuint);
typedef void(*gl21PStencilOp)(GLenum, GLenum, GLenum);
typedef void(*gl21PTexCoord1d)(GLdouble);
typedef void(*gl21PTexCoord1f)(GLfloat);
typedef void(*gl21PTexCoord1i)(GLint);
typedef void(*gl21PTexCoord1s)(GLshort);
typedef void(*gl21PTexCoord2d)(GLdouble, GLdouble);
typedef void(*gl21PTexCoord2f)(GLfloat, GLfloat);
typedef void(*gl21PTexCoord2i)(GLint, GLint);
typedef void(*gl21PTexCoord2s)(GLshort, GLshort);
typedef void(*gl21PTexCoord3d)(GLdouble, GLdouble, GLdouble);
typedef void(*gl21PTexCoord3f)(GLfloat, GLfloat, GLfloat);
typedef void(*gl21PTexCoord3i)(GLint, GLint, GLint);
typedef void(*gl21PTexCoord3s)(GLshort, GLshort, GLshort);
typedef void(*gl21PTexCoord4d)(GLdouble, GLdouble, GLdouble, GLdouble);
typedef void(*gl21PTexCoord4f)(GLfloat, GLfloat, GLfloat, GLfloat);
typedef void(*gl21PTexCoord4i)(GLint, GLint, GLint, GLint);
typedef void(*gl21PTexCoord4s)(GLshort, GLshort, GLshort, GLshort);
typedef void(*gl21PTexCoord1dv)(GLdouble*);
typedef void(*gl21PTexCoord1fv)(GLfloat*);
typedef void(*gl21PTexCoord1iv)(GLint*);
typedef void(*gl21PTexCoord1sv)(GLshort*);
typedef void(*gl21PTexCoord2dv)(GLdouble*);
typedef void(*gl21PTexCoord2fv)(GLfloat*);
typedef void(*gl21PTexCoord2iv)(GLint*);
typedef void(*gl21PTexCoord2sv)(GLshort*);
typedef void(*gl21PTexCoord3dv)(GLdouble*);
typedef void(*gl21PTexCoord3fv)(GLfloat*);
typedef void(*gl21PTexCoord3iv)(GLint*);
typedef void(*gl21PTexCoord3sv)(GLshort*);
typedef void(*gl21PTexCoord4dv)(GLdouble*);
typedef void(*gl21PTexCoord4fv)(GLfloat*);
typedef void(*gl21PTexCoord4iv)(GLint*);
typedef void(*gl21PTexCoord4sv)(GLshort*);
typedef void(*gl21PTexEnvf)(GLenum, GLenum, GLfloat);
typedef void(*gl21PTexEnvi)(GLenum, GLenum, GLint);
typedef void(*gl21PTexEnvfv)(GLenum, GLenum, GLfloat*);
typedef void(*gl21PTexEnviv)(GLenum, GLenum, GLint*);
typedef void(*gl21PTexGend)(GLenum, GLenum, GLdouble);
typedef void(*gl21PTexGenf)(GLenum, GLenum, GLfloat);
typedef void(*gl21PTexGeni)(GLenum, GLenum, GLint);
typedef void(*gl21PTexGendv)(GLenum, GLenum, GLdouble*);
typedef void(*gl21PTexGenfv)(GLenum, GLenum, GLfloat*);
typedef void(*gl21PTexGeniv)(GLenum, GLenum, GLint*);
typedef void(*gl21PTexImage1D)(GLenum, GLint, GLint, GLsizei, GLint, GLenum, GLenum, GLvoid*);
typedef void(*gl21PTexImage2D)(GLenum, GLint, GLint, GLsizei, GLsizei, GLint, GLenum, GLenum, GLvoid*);
typedef void(*gl21PTexParameterf)(GLenum, GLenum, GLfloat);
typedef void(*gl21PTexParameteri)(GLenum, GLenum, GLint);
typedef void(*gl21PTexParameterfv)(GLenum, GLenum, GLfloat*);
typedef void(*gl21PTexParameteriv)(GLenum, GLenum, GLint*);
typedef void(*gl21PTranslated)(GLdouble, GLdouble, GLdouble);
typedef void(*gl21PTranslatef)(GLfloat, GLfloat, GLfloat);
typedef void(*gl21PVertex2s)(GLshort, GLshort);
typedef void(*gl21PVertex2i)(GLint, GLint);
typedef void(*gl21PVertex2f)(GLfloat, GLfloat);
typedef void(*gl21PVertex2d)(GLdouble, GLdouble);
typedef void(*gl21PVertex3s)(GLshort, GLshort, GLshort);
typedef void(*gl21PVertex3i)(GLint, GLint, GLint);
typedef void(*gl21PVertex3f)(GLfloat, GLfloat, GLfloat);
typedef void(*gl21PVertex3d)(GLdouble, GLdouble, GLdouble);
typedef void(*gl21PVertex4s)(GLshort, GLshort, GLshort, GLshort);
typedef void(*gl21PVertex4i)(GLint, GLint, GLint, GLint);
typedef void(*gl21PVertex4f)(GLfloat, GLfloat, GLfloat, GLfloat);
typedef void(*gl21PVertex4d)(GLdouble, GLdouble, GLdouble, GLdouble);
typedef void(*gl21PViewport)(GLint, GLint, GLsizei, GLsizei);
typedef void(*gl21PGetConvolutionParameterfv)(GLenum, GLenum, GLfloat*);
typedef void(*gl21PGetConvolutionParameteriv)(GLenum, GLenum, GLint*);
typedef GLboolean(*gl21PAreTexturesResident)(GLsizei, GLuint*, GLboolean*);
typedef void(*gl21PArrayElement)(GLint);
typedef void(*gl21PDrawArrays)(GLenum, GLint, GLsizei);
typedef void(*gl21PDrawElements)(GLenum, GLsizei, GLenum, GLvoid*);
typedef void(*gl21PGetPointerv)(GLenum, GLvoid*);
typedef void(*gl21PPolygonOffset)(GLfloat, GLfloat);
typedef void(*gl21PCopyTexImage1D)(GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLint);
typedef void(*gl21PCopyTexImage2D)(GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLsizei, GLint);
typedef void(*gl21PCopyTexSubImage1D)(GLenum, GLint, GLint, GLint, GLint, GLsizei);
typedef void(*gl21PCopyTexSubImage2D)(GLenum, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei);
typedef void(*gl21PBindTexture)(GLenum, GLuint);
typedef void(*gl21PDeleteTextures)(GLsizei, GLuint*);
typedef void(*gl21PGenTextures)(GLsizei, GLuint*);
typedef GLboolean(*gl21PIsTexture)(GLuint);
typedef void(*gl21PColorPointer)(GLint, GLenum, GLsizei, GLvoid*);
typedef void(*gl21PEnableClientState)(GLenum);
typedef void(*gl21PDisableClientState)(GLenum);
typedef void(*gl21PIndexub)(GLubyte);
typedef void(*gl21PIndexubv)(GLubyte*);
typedef void(*gl21PInterleavedArrays)(GLenum, GLsizei, GLvoid*);
typedef void(*gl21PNormalPointer)(GLenum, GLsizei, GLvoid*);
typedef void(*gl21PPushClientAttrib)(GLbitfield);
typedef void(*gl21PPrioritizeTextures)(GLsizei, GLuint*, GLclampf*);
typedef void(*gl21PPopClientAttrib)();
typedef void(*gl21PTexCoordPointer)(GLint, GLenum, GLsizei, GLvoid*);
typedef void(*gl21PTexSubImage1D)(GLenum, GLint, GLint, GLsizei, GLenum, GLenum, GLvoid*);
typedef void(*gl21PTexSubImage2D)(GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, GLvoid*);
typedef void(*gl21PVertexPointer)(GLint, GLenum, GLsizei, GLvoid*);
typedef void(*gl21PDrawBuffers)(GLsizei, GLenum*);
typedef void(*gl21PGetActiveAttrib)(GLuint, GLuint, GLsizei, GLsizei*, GLint*, GLenum*, GLchar*);
typedef void(*gl21PGetActiveUniform)(GLuint, GLuint, GLsizei, GLsizei*, GLint*, GLenum*, GLchar*);
typedef void(*gl21PGetAttachedShaders)(GLuint, GLsizei, GLsizei*, GLuint*);
typedef GLint(*gl21PGetAttribLocation)(GLuint, GLchar*);
typedef void(*gl21PGetProgramiv)(GLuint, GLenum, GLint*);
typedef void(*gl21PGetProgramInfoLog)(GLuint, GLsizei, GLsizei*, GLchar*);
typedef void(*gl21PGetShaderiv)(GLuint, GLenum, GLint*);
typedef void(*gl21PGetShaderInfoLog)(GLuint, GLsizei, GLsizei*, GLchar*);
typedef void(*gl21PGetShaderSource)(GLuint, GLsizei, GLsizei*, GLchar*);
typedef void(*gl21PGetUniformfv)(GLuint, GLint, GLfloat*);
typedef void(*gl21PGetUniformiv)(GLuint, GLint, GLint*);
typedef GLint(*gl21PGetUniformLocation)(GLuint, GLchar*);
typedef void(*gl21PGetVertexAttribdv)(GLuint, GLenum, GLdouble*);
typedef void(*gl21PGetVertexAttribfv)(GLuint, GLenum, GLfloat*);
typedef void(*gl21PGetVertexAttribiv)(GLuint, GLenum, GLint*);
typedef void(*gl21PGetVertexAttribPointerv)(GLuint, GLenum, GLvoid*);
typedef GLboolean(*gl21PIsProgram)(GLuint);
typedef GLboolean(*gl21PIsShader)(GLuint);
typedef void(*gl21PLinkProgram)(GLuint);
typedef void(*gl21PShaderSource)(GLuint, GLsizei, GLchar**, GLint*);
typedef void(*gl21PStencilFuncSeparate)(GLenum, GLenum, GLint, GLuint);
typedef void(*gl21PStencilMaskSeparate)(GLenum, GLuint);
typedef void(*gl21PStencilOpSeparate)(GLenum, GLenum, GLenum, GLenum);
typedef void(*gl21PUniform1f)(GLint, GLfloat);
typedef void(*gl21PUniform2f)(GLint, GLfloat, GLfloat);
typedef void(*gl21PUniform3f)(GLint, GLfloat, GLfloat, GLfloat);
typedef void(*gl21PUniform4f)(GLint, GLfloat, GLfloat, GLfloat, GLfloat);
typedef void(*gl21PUniform1i)(GLint, GLint);
typedef void(*gl21PUniform2i)(GLint, GLint, GLint);
typedef void(*gl21PUniform3i)(GLint, GLint, GLint, GLint);
typedef void(*gl21PUniform4i)(GLint, GLint, GLint, GLint, GLint);
typedef void(*gl21PUniform1fv)(GLint, GLsizei, GLfloat*);
typedef void(*gl21PUniform2fv)(GLint, GLsizei, GLfloat*);
typedef void(*gl21PUniform3fv)(GLint, GLsizei, GLfloat*);
typedef void(*gl21PUniform4fv)(GLint, GLsizei, GLfloat*);
typedef void(*gl21PUniform1iv)(GLint, GLsizei, GLint*);
typedef void(*gl21PUniform2iv)(GLint, GLsizei, GLint*);
typedef void(*gl21PUniform3iv)(GLint, GLsizei, GLint*);
typedef void(*gl21PUniform4iv)(GLint, GLsizei, GLint*);
typedef void(*gl21PUseProgram)(GLuint);
typedef void(*gl21PValidateProgram)(GLuint);
typedef void(*gl21PVertexAttribPointer)(GLuint, GLint, GLenum, GLboolean, GLsizei, GLvoid*);
typedef void(*gl21PVertexAttrib1f)(GLuint, GLfloat);
typedef void(*gl21PVertexAttrib1s)(GLuint, GLshort);
typedef void(*gl21PVertexAttrib1d)(GLuint, GLdouble);
typedef void(*gl21PVertexAttrib2f)(GLuint, GLfloat, GLfloat);
typedef void(*gl21PVertexAttrib2s)(GLuint, GLshort, GLshort);
typedef void(*gl21PVertexAttrib2d)(GLuint, GLdouble, GLdouble);
typedef void(*gl21PVertexAttrib3f)(GLuint, GLfloat, GLfloat, GLfloat);
typedef void(*gl21PVertexAttrib3s)(GLuint, GLshort, GLshort, GLshort);
typedef void(*gl21PVertexAttrib3d)(GLuint, GLdouble, GLdouble, GLdouble);
typedef void(*gl21PVertexAttrib4f)(GLuint, GLfloat, GLfloat, GLfloat, GLfloat);
typedef void(*gl21PVertexAttrib4s)(GLuint, GLshort, GLshort, GLshort, GLshort);
typedef void(*gl21PVertexAttrib4d)(GLuint, GLdouble, GLdouble, GLdouble, GLdouble);
typedef void(*gl21PVertexAttrib4Nuv)(GLuint, GLubyte, GLubyte, GLubyte, GLubyte);
typedef void(*gl21PVertexAttrib1fv)(GLuint, GLfloat*);
typedef void(*gl21PVertexAttrib1sv)(GLuint, GLshort*);
typedef void(*gl21PVertexAttrib1dv)(GLuint, GLdouble*);
typedef void(*gl21PVertexAttrib2fv)(GLuint, GLfloat*);
typedef void(*gl21PVertexAttrib2sv)(GLuint, GLshort*);
typedef void(*gl21PVertexAttrib2dv)(GLuint, GLdouble*);
typedef void(*gl21PVertexAttrib3fv)(GLuint, GLfloat*);
typedef void(*gl21PVertexAttrib3sv)(GLuint, GLshort*);
typedef void(*gl21PVertexAttrib3dv)(GLuint, GLdouble*);
typedef void(*gl21PVertexAttrib4fv)(GLuint, GLfloat*);
typedef void(*gl21PVertexAttrib4sv)(GLuint, GLshort*);
typedef void(*gl21PVertexAttrib4dv)(GLuint, GLdouble*);
typedef void(*gl21PVertexAttrib4iv)(GLuint, GLint*);
typedef void(*gl21PVertexAttrib4bv)(GLuint, GLbyte*);
typedef void(*gl21PVertexAttrib4ubv)(GLuint, GLubyte*);
typedef void(*gl21PVertexAttrib4usv)(GLuint, GLushort*);
typedef void(*gl21PVertexAttrib4uiv)(GLuint, GLuint*);
typedef void(*gl21PVertexAttrib4Nbv)(GLuint, GLbyte*);
typedef void(*gl21PVertexAttrib4Nsv)(GLuint, GLshort*);
typedef void(*gl21PVertexAttrib4Niv)(GLuint, GLint*);
typedef void(*gl21PVertexAttrib4Nubv)(GLuint, GLubyte*);
typedef void(*gl21PVertexAttrib4Nusv)(GLuint, GLushort*);
typedef void(*gl21PVertexAttrib4Nuiv)(GLuint, GLuint*);
typedef void(*gl21PUniformMatrix2fv)(GLint, GLsizei, GLboolean, GLfloat*);
typedef void(*gl21PUniformMatrix3fv)(GLint, GLsizei, GLboolean, GLfloat*);
typedef void(*gl21PUniformMatrix4fv)(GLint, GLsizei, GLboolean, GLfloat*);
typedef void(*gl21PUniformMatrix2x3fv)(GLint, GLsizei, GLboolean, GLfloat*);
typedef void(*gl21PUniformMatrix3x2fv)(GLint, GLsizei, GLboolean, GLfloat*);
typedef void(*gl21PUniformMatrix2x4fv)(GLint, GLsizei, GLboolean, GLfloat*);
typedef void(*gl21PUniformMatrix4x2fv)(GLint, GLsizei, GLboolean, GLfloat*);
typedef void(*gl21PUniformMatrix3x4fv)(GLint, GLsizei, GLboolean, GLfloat*);
typedef void(*gl21PUniformMatrix4x3fv)(GLint, GLsizei, GLboolean, GLfloat*);
typedef void(*gl21PColorTable)(GLenum, GLenum, GLsizei, GLenum, GLenum, GLvoid*);
typedef void(*gl21PColorTableParameterfv)(GLenum, GLenum, GLfloat*);
typedef void(*gl21PColorTableParameteriv)(GLenum, GLenum, GLint*);
typedef void(*gl21PColorSubTable)(GLenum, GLsizei, GLsizei, GLenum, GLenum, GLvoid*);
typedef void(*gl21PConvolutionFilter1D)(GLenum, GLenum, GLsizei, GLenum, GLenum, GLvoid*);
typedef void(*gl21PConvolutionFilter2D)(GLenum, GLenum, GLsizei, GLsizei, GLenum, GLenum, GLvoid*);
typedef void(*gl21PConvolutionParameterf)(GLenum, GLenum, GLfloat);
typedef void(*gl21PConvolutionParameteri)(GLenum, GLenum, GLint);
typedef void(*gl21PCopyColorTable)(GLenum, GLenum, GLint, GLint, GLsizei);
typedef void(*gl21PCopyColorSubTable)(GLenum, GLsizei, GLint, GLint, GLsizei);
typedef void(*gl21PCopyConvolutionFilter1D)(GLenum, GLenum, GLint, GLint, GLsizei);
typedef void(*gl21PCopyConvolutionFilter2D)(GLenum, GLenum, GLint, GLint, GLsizei, GLsizei);
typedef void(*gl21PGetColorTable)(GLenum, GLenum, GLenum, GLvoid*);
typedef void(*gl21PGetColorTableParameterfv)(GLenum, GLenum, GLfloat*);
typedef void(*gl21PGetColorTableParameteriv)(GLenum, GLenum, GLint*);
typedef void(*gl21PGetConvolutionFilter)(GLenum, GLenum, GLenum, GLvoid*);
typedef void(*gl21PGetHistogram)(GLenum, GLboolean, GLenum, GLenum, GLvoid*);
typedef void(*gl21PGetHistogramParameterfv)(GLenum, GLenum, GLfloat*);
typedef void(*gl21PGetHistogramParameteriv)(GLenum, GLenum, GLint*);
typedef void(*gl21PGetSeparableFilter)(GLenum, GLenum, GLenum, GLvoid*, GLvoid*, GLvoid*);
typedef void(*gl21PHistogram)(GLenum, GLsizei, GLenum, GLboolean);
typedef void(*gl21PMinmax)(GLenum, GLenum, GLboolean);
typedef void(*gl21PMultiTexCoord1s)(GLenum, GLshort);
typedef void(*gl21PMultiTexCoord1i)(GLenum, GLint);
typedef void(*gl21PMultiTexCoord1f)(GLenum, GLfloat);
typedef void(*gl21PMultiTexCoord1d)(GLenum, GLdouble);
typedef void(*gl21PMultiTexCoord2s)(GLenum, GLshort, GLshort);
typedef void(*gl21PMultiTexCoord2i)(GLenum, GLint, GLint);
typedef void(*gl21PMultiTexCoord2f)(GLenum, GLfloat, GLfloat);
typedef void(*gl21PMultiTexCoord2d)(GLenum, GLdouble, GLdouble);
typedef void(*gl21PMultiTexCoord3s)(GLenum, GLshort, GLshort, GLshort);
typedef void(*gl21PMultiTexCoord3i)(GLenum, GLint, GLint, GLint);
typedef void(*gl21PMultiTexCoord3f)(GLenum, GLfloat, GLfloat, GLfloat);
typedef void(*gl21PMultiTexCoord3d)(GLenum, GLdouble, GLdouble, GLdouble);
typedef void(*gl21PMultiTexCoord4s)(GLenum, GLshort, GLshort, GLshort, GLshort);
typedef void(*gl21PMultiTexCoord4i)(GLenum, GLint, GLint, GLint, GLint);
typedef void(*gl21PMultiTexCoord4f)(GLenum, GLfloat, GLfloat, GLfloat, GLfloat);
typedef void(*gl21PMultiTexCoord4d)(GLenum, GLdouble, GLdouble, GLdouble, GLdouble);
typedef void(*gl21PMultiTexCoord1sv)(GLenum, GLshort*);
typedef void(*gl21PMultiTexCoord1iv)(GLenum, GLint*);
typedef void(*gl21PMultiTexCoord1fv)(GLenum, GLfloat*);
typedef void(*gl21PMultiTexCoord1dv)(GLenum, GLdouble*);
typedef void(*gl21PMultiTexCoord2sv)(GLenum, GLshort*);
typedef void(*gl21PMultiTexCoord2iv)(GLenum, GLint*);
typedef void(*gl21PMultiTexCoord2fv)(GLenum, GLfloat*);
typedef void(*gl21PMultiTexCoord2dv)(GLenum, GLdouble*);
typedef void(*gl21PMultiTexCoord3sv)(GLenum, GLshort*);
typedef void(*gl21PMultiTexCoord3iv)(GLenum, GLint*);
typedef void(*gl21PMultiTexCoord3fv)(GLenum, GLfloat*);
typedef void(*gl21PMultiTexCoord3dv)(GLenum, GLdouble*);
typedef void(*gl21PMultiTexCoord4sv)(GLenum, GLshort*);
typedef void(*gl21PMultiTexCoord4iv)(GLenum, GLint*);
typedef void(*gl21PMultiTexCoord4fv)(GLenum, GLfloat*);
typedef void(*gl21PMultiTexCoord4dv)(GLenum, GLdouble*);
typedef void(*gl21PResetHistogram)(GLenum);
typedef void(*gl21PResetMinmax)(GLenum);
typedef void(*gl21PSeparableFilter2D)(GLenum, GLenum, GLsizei, GLsizei, GLenum, GLenum, GLvoid*, GLvoid*);
typedef void(*gl21PBlendColor)(GLclampf, GLclampf, GLclampf, GLclampf);
typedef void(*gl21PBlendEquation)(GLenum);
typedef void(*gl21PCopyTexSubImage3D)(GLenum, GLint, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei);
typedef void(*gl21PDrawRangeElements)(GLenum, GLuint, GLuint, GLsizei, GLenum, GLvoid*);
typedef void(*gl21PTexImage3D)(GLenum, GLint, GLint, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, GLvoid*);
typedef void(*gl21PTexSubImage3D)(GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLenum, GLvoid*);
typedef void(*gl21PActiveTexture)(GLenum);
typedef void(*gl21PClientActiveTexture)(GLenum);
typedef void(*gl21PCompressedTexImage1D)(GLenum, GLint, GLenum, GLsizei, GLint, GLsizei, GLvoid*);
typedef void(*gl21PCompressedTexImage2D)(GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, GLvoid*);
typedef void(*gl21PCompressedTexImage3D)(GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLsizei, GLvoid*);
typedef void(*gl21PCompressedTexSubImage1D)(GLenum, GLint, GLint, GLsizei, GLenum, GLsizei, GLvoid*);
typedef void(*gl21PCompressedTexSubImage2D)(GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, GLvoid*);
typedef void(*gl21PCompressedTexSubImage3D)(GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLsizei, GLvoid*);
typedef void(*gl21PGetCompressedTexImage)(GLenum, GLint, GLvoid*);
typedef void(*gl21PLoadTransposeMatrixd)(GLdouble*);
typedef void(*gl21PLoadTransposeMatrixf)(GLdouble*);
typedef void(*gl21PMultTransposeMatrixd)(GLdouble*);
typedef void(*gl21PMultTransposeMatrixf)(GLfloat*);
typedef void(*gl21PSampleCoverage)(GLclampf, GLboolean);
typedef void(*gl21PBlendFuncSeparate)(GLenum, GLenum, GLenum, GLenum);
typedef void(*gl21PFogCoordPointer)(GLenum, GLsizei, GLvoid*);
typedef void(*gl21PFogCoordd)(GLdouble);
typedef void(*gl21PFogCoordf)(GLfloat);
typedef void(*gl21PFogCoorddv)(GLdouble*);
typedef void(*gl21PFogCoordfv)(GLfloat*);
typedef void(*gl21PMultiDrawArrays)(GLenum, GLint*, GLsizei*, GLsizei);
typedef void(*gl21PMultiDrawElements)(GLenum, GLsizei*, GLenum, GLvoid*, GLsizei);
typedef void(*gl21PPointParameterf)(GLenum, GLfloat);
typedef void(*gl21PPointParameteri)(GLenum, GLint);
typedef void(*gl21PSecondaryColor3b)(GLbyte, GLbyte, GLbyte);
typedef void(*gl21PSecondaryColor3s)(GLshort, GLshort, GLshort);
typedef void(*gl21PSecondaryColor3i)(GLint, GLint, GLint);
typedef void(*gl21PSecondaryColor3f)(GLfloat, GLfloat, GLfloat);
typedef void(*gl21PSecondaryColor3d)(GLdouble, GLdouble, GLdouble);
typedef void(*gl21PSecondaryColor3ub)(GLubyte, GLubyte, GLubyte);
typedef void(*gl21PSecondaryColor3us)(GLushort, GLushort, GLushort);
typedef void(*gl21PSecondaryColor3ui)(GLuint, GLuint, GLuint);
typedef void(*gl21PSecondaryColor3bv)(GLbyte*);
typedef void(*gl21PSecondaryColor3sv)(GLshort*);
typedef void(*gl21PSecondaryColor3iv)(GLint*);
typedef void(*gl21PSecondaryColor3fv)(GLfloat*);
typedef void(*gl21PSecondaryColor3dv)(GLdouble*);
typedef void(*gl21PSecondaryColor3ubv)(GLubyte*);
typedef void(*gl21PSecondaryColor3usv)(GLushort*);
typedef void(*gl21PSecondaryColor3uiv)(GLuint*);
typedef void(*gl21PSecondaryColorPointer)(GLint, GLenum, GLsizei, GLvoid*);
typedef void(*gl21PWindowPos2s)(GLshort, GLshort);
typedef void(*gl21PWindowPos2i)(GLint, GLint);
typedef void(*gl21PWindowPos2f)(GLfloat, GLfloat);
typedef void(*gl21PWindowPos2d)(GLdouble, GLdouble);
typedef void(*gl21PWindowPos3s)(GLshort, GLshort, GLshort);
typedef void(*gl21PWindowPos3i)(GLint, GLint, GLint);
typedef void(*gl21PWindowPos3f)(GLfloat, GLfloat, GLfloat);
typedef void(*gl21PWindowPos3d)(GLdouble, GLdouble, GLdouble);
typedef void(*gl21PWindowPos2sv)(GLshort*);
typedef void(*gl21PWindowPos2iv)(GLint*);
typedef void(*gl21PWindowPos2fv)(GLfloat*);
typedef void(*gl21PWindowPos2dv)(GLdouble*);
typedef void(*gl21PWindowPos3sv)(GLshort*);
typedef void(*gl21PWindowPos3iv)(GLint*);
typedef void(*gl21PWindowPos3fv)(GLfloat*);
typedef void(*gl21PWindowPos3dv)(GLdouble*);
typedef void(*gl21PBeginQuery)(GLenum, GLuint);
typedef void(*gl21PBindBuffer)(GLenum, GLuint);
typedef void(*gl21PBufferData)(GLenum, GLsizeiptr, GLvoid*, GLenum);
typedef void(*gl21PBufferSubData)(GLenum, GLenum, GLsizeiptr, GLvoid*);
typedef void(*gl21PDeleteBuffers)(GLsizei, GLuint*);
typedef void(*gl21PDeleteQueries)(GLsizei, GLuint*);
typedef void(*gl21PGenBuffers)(GLsizei, GLuint*);
typedef void(*gl21PGenQueries)(GLsizei, GLuint*);
typedef void(*gl21PGetBufferParameteriv)(GLenum, GLenum, GLint*);
typedef void(*gl21PGetBufferPointerv)(GLenum, GLenum, GLvoid*);
typedef void(*gl21PGetBufferSubData)(GLenum, GLintptr, GLsizeiptr, GLvoid*);
typedef void(*gl21PGetQueryObjectiv)(GLuint, GLenum, GLint*);
typedef void(*gl21PGetQueryObjectuiv)(GLuint, GLenum, GLuint*);
typedef void(*gl21PGetQueryiv)(GLenum, GLenum, GLint*);
typedef GLboolean(*gl21PIsBuffer)(GLuint);
typedef GLboolean(*gl21PIsQuery)(GLuint);
typedef GLvoid*(*gl21PMapBuffer)(GLenum, GLenum);
typedef GLboolean(*gl21PUnmapBuffer)(GLenum);
typedef void(*gl21PAttachShader)(GLuint, GLuint);
typedef void(*gl21PBindAttribLocation)(GLuint, GLuint, GLchar*);
typedef void(*gl21PBlendEquationSeperate)(GLenum, GLenum);
typedef void(*gl21PCompileShader)(GLuint);
typedef GLuint(*gl21PCreateProgram)();
typedef GLuint(*gl21PCreateShader)(GLenum);
typedef void(*gl21PDeleteProgram)(GLuint);
typedef void(*gl21PDeleteShader)(GLuint);
typedef void(*gl21PDetachShader)(GLuint, GLuint);
typedef void(*gl21PEnableVertexAttribArray)(GLuint);
typedef void(*gl21PDisableVertexAttribArray)(GLuint);

typedef struct {
    gl21PAccum fnAccum;
    gl21PAlphaFunc fnAlphaFunc;
    gl21PBegin fnBegin;
    gl21PEnd fnEnd;
    gl21PBitmap fnBitmap;
    gl21PBlendFunc fnBlendFunc;
    gl21PCallList fnCallList;
    gl21PCallLists fnCallLists;
    gl21PClear fnClear;
    gl21PClearAccum fnClearAccum;
    gl21PClearColor fnClearColor;
    gl21PClearDepth fnClearDepth;
    gl21PClearIndex fnClearIndex;
    gl21PClearStencil fnClearStencil;
    gl21PClipPlane fnClipPlane;
    gl21PColor3b fnColor3b;
    gl21PColor3d fnColor3d;
    gl21PColor3f fnColor3f;
    gl21PColor3i fnColor3i;
    gl21PColor3s fnColor3s;
    gl21PColor3ub fnColor3ub;
    gl21PColor3ui fnColor3ui;
    gl21PColor3us fnColor3us;
    gl21PColor4b fnColor4b;
    gl21PColor4d fnColor4d;
    gl21PColor4f fnColor4f;
    gl21PColor4i fnColor4i;
    gl21PColor4s fnColor4s;
    gl21PColor4ub fnColor4ub;
    gl21PColor4ui fnColor4ui;
    gl21PColor4us fnColor4us;
    gl21PColor3bv fnColor3bv;
    gl21PColor3dv fnColor3dv;
    gl21PColor3fv fnColor3fv;
    gl21PColor3iv fnColor3iv;
    gl21PColor3sv fnColor3sv;
    gl21PColor3ubv fnColor3ubv;
    gl21PColor3uiv fnColor3uiv;
    gl21PColor3usv fnColor3usv;
    gl21PColor4bv fnColor4bv;
    gl21PColor4dv fnColor4dv;
    gl21PColor4fv fnColor4fv;
    gl21PColor4iv fnColor4iv;
    gl21PColor4sv fnColor4sv;
    gl21PColor4ubv fnColor4ubv;
    gl21PColor4uiv fnColor4uiv;
    gl21PColor4usv fnColor4usv;
    gl21PColorMask fnColorMask;
    gl21PColorMaterial fnColorMaterial;
    gl21PCopyPixels fnCopyPixels;
    gl21PCullFace fnCullFace;
    gl21PDeleteLists fnDeleteLists;
    gl21PDepthFunc fnDepthFunc;
    gl21PDepthMask fnDepthMask;
    gl21PDepthRange fnDepthRange;
    gl21PEnable fnEnable;
    gl21PDisable fnDisable;
    gl21PDrawBuffer fnDrawBuffer;
    gl21PDrawPixels fnDrawPixels;
    gl21PEdgeFlag fnEdgeFlag;
    gl21PEdgeFlagv fnEdgeFlagv;
    gl21PEdgeFlagPointer fnEdgeFlagPointer;
    gl21PEvalCoord1d fnEvalCoord1d;
    gl21PEvalCoord1f fnEvalCoord1f;
    gl21PEvalCoord2d fnEvalCoord2d;
    gl21PEvalCoord2f fnEvalCoord2f;
    gl21PEvalCoord1dv fnEvalCoord1dv;
    gl21PEvalCoord1fv fnEvalCoord1fv;
    gl21PEvalCoord2dv fnEvalCoord2dv;
    gl21PEvalCoord2fv fnEvalCoord2fv;
    gl21PEvalMesh1 fnEvalMesh1;
    gl21PEvalMesh2 fnEvalMesh2;
    gl21PEvalPoint1 fnEvalPoint1;
    gl21PEvalPoint2 fnEvalPoint2;
    gl21PFeedbackBuffer fnFeedbackBuffer;
    gl21PFinish fnFinish;
    gl21PFlush fnFlush;
    gl21PFogf fnFogf;
    gl21PFogi fnFogi;
    gl21PFogfv fnFogfv;
    gl21PFogiv fnFogiv;
    gl21PFrontFace fnFrontFace;
    gl21PFrustum fnFrustum;
    gl21PGenLists fnGenLists;
    gl21PGetBooleanv fnGetBooleanv;
    gl21PGetDoublev fnGetDoublev;
    gl21PGetFloatv fnGetFloatv;
    gl21PGetIntegerv fnGetIntegerv;
    gl21PGetClipPlane fnGetClipPlane;
    gl21PGetError fnGetError;
    gl21PGetLightfv fnGetLightfv;
    gl21PGetLightiv fnGetLightiv;
    gl21PGetMapdv fnGetMapdv;
    gl21PGetMapfv fnGetMapfv;
    gl21PGetMapiv fnGetMapiv;
    gl21PGetMaterialfv fnGetMaterialfv;
    gl21PGetMaterialiv fnGetMaterialiv;
    gl21PGetPixelMapfv fnGetPixelMapfv;
    gl21PGetPixelMapuiv fnGetPixelMapuiv;
    gl21PGetPixelMapusv fnGetPixelMapusv;
    gl21PGetPolygonStipple fnGetPolygonStipple;
    gl21PGetString fnGetString;
    gl21PGetTexEnvfv fnGetTexEnvfv;
    gl21PGetTexEnviv fnGetTexEnviv;
    gl21PGetTexGendv fnGetTexGendv;
    gl21PGetTexGenfv fnGetTexGenfv;
    gl21PGetTexGeniv fnGetTexGeniv;
    gl21PGetTexImage fnGetTexImage;
    gl21PGetTexLevelParameterfv fnGetTexLevelParameterfv;
    gl21PGetTexLevelParameteriv fnGetTexLevelParameteriv;
    gl21PGetTexParameterfv fnGetTexParameterfv;
    gl21PGetTexParameteriv fnGetTexParameteriv;
    gl21PHint fnHint;
    gl21PIndexd fnIndexd;
    gl21PIndexf fnIndexf;
    gl21PIndexi fnIndexi;
    gl21PIndexs fnIndexs;
    gl21PIndexdv fnIndexdv;
    gl21PIndexfv fnIndexfv;
    gl21PIndexiv fnIndexiv;
    gl21PIndexsv fnIndexsv;
    gl21PIndexMask fnIndexMask;
    gl21PIndexPointer fnIndexPointer;
    gl21PInitNames fnInitNames;
    gl21PIsEnabled fnIsEnabled;
    gl21PIsList fnIsList;
    gl21PLightf fnLightf;
    gl21PLighti fnLighti;
    gl21PLightfv fnLightfv;
    gl21PLightiv fnLightiv;
    gl21PLightModelf fnLightModelf;
    gl21PLightModeli fnLightModeli;
    gl21PLightModelfv fnLightModelfv;
    gl21PLightModeliv fnLightModeliv;
    gl21PLineStipple fnLineStipple;
    gl21PLineWidth fnLineWidth;
    gl21PListBase fnListBase;
    gl21PLoadIdentity fnLoadIdentity;
    gl21PLoadMatrixd fnLoadMatrixd;
    gl21PLoadMatrixf fnLoadMatrixf;
    gl21PLoadName fnLoadName;
    gl21PLogicOp fnLogicOp;
    gl21PMap1d fnMap1d;
    gl21PMap1f fnMap1f;
    gl21PMap2d fnMap2d;
    gl21PMap2f fnMap2f;
    gl21PMapGrid1d fnMapGrid1d;
    gl21PMapGrid1f fnMapGrid1f;
    gl21PMapGrid2d fnMapGrid2d;
    gl21PMapGrid2f fnMapGrid2f;
    gl21PMaterialf fnMaterialf;
    gl21PMateriali fnMateriali;
    gl21PMaterialfv fnMaterialfv;
    gl21PMaterialiv fnMaterialiv;
    gl21PMatrixMode fnMatrixMode;
    gl21PMultMatrixd fnMultMatrixd;
    gl21PMultMatrixf fnMultMatrixf;
    gl21PNewList fnNewList;
    gl21PEndList fnEndList;
    gl21PNormal3b fnNormal3b;
    gl21PNormal3d fnNormal3d;
    gl21PNormal3f fnNormal3f;
    gl21PNormal3i fnNormal3i;
    gl21PNormal3s fnNormal3s;
    gl21PNormal3bv fnNormal3bv;
    gl21PNormal3dv fnNormal3dv;
    gl21PNormal3fv fnNormal3fv;
    gl21PNormal3iv fnNormal3iv;
    gl21PNormal3sv fnNormal3sv;
    gl21POrtho fnOrtho;
    gl21PPassThrough fnPassThrough;
    gl21PPixelMapfv fnPixelMapfv;
    gl21PPixelMapuiv fnPixelMapuiv;
    gl21PPixelMapusv fnPixelMapusv;
    gl21PPixelStoref fnPixelStoref;
    gl21PPixelStorei fnPixelStorei;
    gl21PPixelTransferf fnPixelTransferf;
    gl21PPixelTransferi fnPixelTransferi;
    gl21PPixelZoom fnPixelZoom;
    gl21PPointSize fnPointSize;
    gl21PPolygonMode fnPolygonMode;
    gl21PPolygonStipple fnPolygonStipple;
    gl21PPushAttrib fnPushAttrib;
    gl21PPopAttrib fnPopAttrib;
    gl21PPushMatrix fnPushMatrix;
    gl21PPopMatrix fnPopMatrix;
    gl21PPushName fnPushName;
    gl21PPopName fnPopName;
    gl21PRasterPos2d fnRasterPos2d;
    gl21PRasterPos2f fnRasterPos2f;
    gl21PRasterPos2i fnRasterPos2i;
    gl21PRasterPos2s fnRasterPos2s;
    gl21PRasterPos3d fnRasterPos3d;
    gl21PRasterPos3f fnRasterPos3f;
    gl21PRasterPos3i fnRasterPos3i;
    gl21PRasterPos3s fnRasterPos3s;
    gl21PRasterPos4d fnRasterPos4d;
    gl21PRasterPos4f fnRasterPos4f;
    gl21PRasterPos4i fnRasterPos4i;
    gl21PRasterPos4s fnRasterPos4s;
    gl21PRasterPos2dv fnRasterPos2dv;
    gl21PRasterPos2fv fnRasterPos2fv;
    gl21PRasterPos2iv fnRasterPos2iv;
    gl21PRasterPos2sv fnRasterPos2sv;
    gl21PRasterPos3dv fnRasterPos3dv;
    gl21PRasterPos3fv fnRasterPos3fv;
    gl21PRasterPos3iv fnRasterPos3iv;
    gl21PRasterPos3sv fnRasterPos3sv;
    gl21PRasterPos4dv fnRasterPos4dv;
    gl21PRasterPos4fv fnRasterPos4fv;
    gl21PRasterPos4iv fnRasterPos4iv;
    gl21PRasterPos4sv fnRasterPos4sv;
    gl21PReadBuffer fnReadBuffer;
    gl21PReadPixels fnReadPixels;
    gl21PRectd fnRectd;
    gl21PRectf fnRectf;
    gl21PRecti fnRecti;
    gl21PRects fnRects;
    gl21PRectdv fnRectdv;
    gl21PRectfv fnRectfv;
    gl21PRectiv fnRectiv;
    gl21PRectsv fnRectsv;
    gl21PRenderMode fnRenderMode;
    gl21PRotated fnRotated;
    gl21PRotatef fnRotatef;
    gl21PScaled fnScaled;
    gl21PScalef fnScalef;
    gl21PScissor fnScissor;
    gl21PSelectBuffer fnSelectBuffer;
    gl21PShadeModel fnShadeModel;
    gl21PStencilFunc fnStencilFunc;
    gl21PStencilMask fnStencilMask;
    gl21PStencilOp fnStencilOp;
    gl21PTexCoord1d fnTexCoord1d;
    gl21PTexCoord1f fnTexCoord1f;
    gl21PTexCoord1i fnTexCoord1i;
    gl21PTexCoord1s fnTexCoord1s;
    gl21PTexCoord2d fnTexCoord2d;
    gl21PTexCoord2f fnTexCoord2f;
    gl21PTexCoord2i fnTexCoord2i;
    gl21PTexCoord2s fnTexCoord2s;
    gl21PTexCoord3d fnTexCoord3d;
    gl21PTexCoord3f fnTexCoord3f;
    gl21PTexCoord3i fnTexCoord3i;
    gl21PTexCoord3s fnTexCoord3s;
    gl21PTexCoord4d fnTexCoord4d;
    gl21PTexCoord4f fnTexCoord4f;
    gl21PTexCoord4i fnTexCoord4i;
    gl21PTexCoord4s fnTexCoord4s;
    gl21PTexCoord1dv fnTexCoord1dv;
    gl21PTexCoord1fv fnTexCoord1fv;
    gl21PTexCoord1iv fnTexCoord1iv;
    gl21PTexCoord1sv fnTexCoord1sv;
    gl21PTexCoord2dv fnTexCoord2dv;
    gl21PTexCoord2fv fnTexCoord2fv;
    gl21PTexCoord2iv fnTexCoord2iv;
    gl21PTexCoord2sv fnTexCoord2sv;
    gl21PTexCoord3dv fnTexCoord3dv;
    gl21PTexCoord3fv fnTexCoord3fv;
    gl21PTexCoord3iv fnTexCoord3iv;
    gl21PTexCoord3sv fnTexCoord3sv;
    gl21PTexCoord4dv fnTexCoord4dv;
    gl21PTexCoord4fv fnTexCoord4fv;
    gl21PTexCoord4iv fnTexCoord4iv;
    gl21PTexCoord4sv fnTexCoord4sv;
    gl21PTexEnvf fnTexEnvf;
    gl21PTexEnvi fnTexEnvi;
    gl21PTexEnvfv fnTexEnvfv;
    gl21PTexEnviv fnTexEnviv;
    gl21PTexGend fnTexGend;
    gl21PTexGenf fnTexGenf;
    gl21PTexGeni fnTexGeni;
    gl21PTexGendv fnTexGendv;
    gl21PTexGenfv fnTexGenfv;
    gl21PTexGeniv fnTexGeniv;
    gl21PTexImage1D fnTexImage1D;
    gl21PTexImage2D fnTexImage2D;
    gl21PTexParameterf fnTexParameterf;
    gl21PTexParameteri fnTexParameteri;
    gl21PTexParameterfv fnTexParameterfv;
    gl21PTexParameteriv fnTexParameteriv;
    gl21PTranslated fnTranslated;
    gl21PTranslatef fnTranslatef;
    gl21PVertex2s fnVertex2s;
    gl21PVertex2i fnVertex2i;
    gl21PVertex2f fnVertex2f;
    gl21PVertex2d fnVertex2d;
    gl21PVertex3s fnVertex3s;
    gl21PVertex3i fnVertex3i;
    gl21PVertex3f fnVertex3f;
    gl21PVertex3d fnVertex3d;
    gl21PVertex4s fnVertex4s;
    gl21PVertex4i fnVertex4i;
    gl21PVertex4f fnVertex4f;
    gl21PVertex4d fnVertex4d;
    gl21PViewport fnViewport;
    gl21PGetConvolutionParameterfv fnGetConvolutionParameterfv;
    gl21PGetConvolutionParameteriv fnGetConvolutionParameteriv;
    gl21PAreTexturesResident fnAreTexturesResident;
    gl21PArrayElement fnArrayElement;
    gl21PDrawArrays fnDrawArrays;
    gl21PDrawElements fnDrawElements;
    gl21PGetPointerv fnGetPointerv;
    gl21PPolygonOffset fnPolygonOffset;
    gl21PCopyTexImage1D fnCopyTexImage1D;
    gl21PCopyTexImage2D fnCopyTexImage2D;
    gl21PCopyTexSubImage1D fnCopyTexSubImage1D;
    gl21PCopyTexSubImage2D fnCopyTexSubImage2D;
    gl21PBindTexture fnBindTexture;
    gl21PDeleteTextures fnDeleteTextures;
    gl21PGenTextures fnGenTextures;
    gl21PIsTexture fnIsTexture;
    gl21PColorPointer fnColorPointer;
    gl21PEnableClientState fnEnableClientState;
    gl21PDisableClientState fnDisableClientState;
    gl21PIndexub fnIndexub;
    gl21PIndexubv fnIndexubv;
    gl21PInterleavedArrays fnInterleavedArrays;
    gl21PNormalPointer fnNormalPointer;
    gl21PPushClientAttrib fnPushClientAttrib;
    gl21PPrioritizeTextures fnPrioritizeTextures;
    gl21PPopClientAttrib fnPopClientAttrib;
    gl21PTexCoordPointer fnTexCoordPointer;
    gl21PTexSubImage1D fnTexSubImage1D;
    gl21PTexSubImage2D fnTexSubImage2D;
    gl21PVertexPointer fnVertexPointer;
    gl21PDrawBuffers fnDrawBuffers;
    gl21PGetActiveAttrib fnGetActiveAttrib;
    gl21PGetActiveUniform fnGetActiveUniform;
    gl21PGetAttachedShaders fnGetAttachedShaders;
    gl21PGetAttribLocation fnGetAttribLocation;
    gl21PGetProgramiv fnGetProgramiv;
    gl21PGetProgramInfoLog fnGetProgramInfoLog;
    gl21PGetShaderiv fnGetShaderiv;
    gl21PGetShaderInfoLog fnGetShaderInfoLog;
    gl21PGetShaderSource fnGetShaderSource;
    gl21PGetUniformfv fnGetUniformfv;
    gl21PGetUniformiv fnGetUniformiv;
    gl21PGetUniformLocation fnGetUniformLocation;
    gl21PGetVertexAttribdv fnGetVertexAttribdv;
    gl21PGetVertexAttribfv fnGetVertexAttribfv;
    gl21PGetVertexAttribiv fnGetVertexAttribiv;
    gl21PGetVertexAttribPointerv fnGetVertexAttribPointerv;
    gl21PIsProgram fnIsProgram;
    gl21PIsShader fnIsShader;
    gl21PLinkProgram fnLinkProgram;
    gl21PShaderSource fnShaderSource;
    gl21PStencilFuncSeparate fnStencilFuncSeparate;
    gl21PStencilMaskSeparate fnStencilMaskSeparate;
    gl21PStencilOpSeparate fnStencilOpSeparate;
    gl21PUniform1f fnUniform1f;
    gl21PUniform2f fnUniform2f;
    gl21PUniform3f fnUniform3f;
    gl21PUniform4f fnUniform4f;
    gl21PUniform1i fnUniform1i;
    gl21PUniform2i fnUniform2i;
    gl21PUniform3i fnUniform3i;
    gl21PUniform4i fnUniform4i;
    gl21PUniform1fv fnUniform1fv;
    gl21PUniform2fv fnUniform2fv;
    gl21PUniform3fv fnUniform3fv;
    gl21PUniform4fv fnUniform4fv;
    gl21PUniform1iv fnUniform1iv;
    gl21PUniform2iv fnUniform2iv;
    gl21PUniform3iv fnUniform3iv;
    gl21PUniform4iv fnUniform4iv;
    gl21PUseProgram fnUseProgram;
    gl21PValidateProgram fnValidateProgram;
    gl21PVertexAttribPointer fnVertexAttribPointer;
    gl21PVertexAttrib1f fnVertexAttrib1f;
    gl21PVertexAttrib1s fnVertexAttrib1s;
    gl21PVertexAttrib1d fnVertexAttrib1d;
    gl21PVertexAttrib2f fnVertexAttrib2f;
    gl21PVertexAttrib2s fnVertexAttrib2s;
    gl21PVertexAttrib2d fnVertexAttrib2d;
    gl21PVertexAttrib3f fnVertexAttrib3f;
    gl21PVertexAttrib3s fnVertexAttrib3s;
    gl21PVertexAttrib3d fnVertexAttrib3d;
    gl21PVertexAttrib4f fnVertexAttrib4f;
    gl21PVertexAttrib4s fnVertexAttrib4s;
    gl21PVertexAttrib4d fnVertexAttrib4d;
    gl21PVertexAttrib4Nuv fnVertexAttrib4Nuv;
    gl21PVertexAttrib1fv fnVertexAttrib1fv;
    gl21PVertexAttrib1sv fnVertexAttrib1sv;
    gl21PVertexAttrib1dv fnVertexAttrib1dv;
    gl21PVertexAttrib2fv fnVertexAttrib2fv;
    gl21PVertexAttrib2sv fnVertexAttrib2sv;
    gl21PVertexAttrib2dv fnVertexAttrib2dv;
    gl21PVertexAttrib3fv fnVertexAttrib3fv;
    gl21PVertexAttrib3sv fnVertexAttrib3sv;
    gl21PVertexAttrib3dv fnVertexAttrib3dv;
    gl21PVertexAttrib4fv fnVertexAttrib4fv;
    gl21PVertexAttrib4sv fnVertexAttrib4sv;
    gl21PVertexAttrib4dv fnVertexAttrib4dv;
    gl21PVertexAttrib4iv fnVertexAttrib4iv;
    gl21PVertexAttrib4bv fnVertexAttrib4bv;
    gl21PVertexAttrib4ubv fnVertexAttrib4ubv;
    gl21PVertexAttrib4usv fnVertexAttrib4usv;
    gl21PVertexAttrib4uiv fnVertexAttrib4uiv;
    gl21PVertexAttrib4Nbv fnVertexAttrib4Nbv;
    gl21PVertexAttrib4Nsv fnVertexAttrib4Nsv;
    gl21PVertexAttrib4Niv fnVertexAttrib4Niv;
    gl21PVertexAttrib4Nubv fnVertexAttrib4Nubv;
    gl21PVertexAttrib4Nusv fnVertexAttrib4Nusv;
    gl21PVertexAttrib4Nuiv fnVertexAttrib4Nuiv;
    gl21PUniformMatrix2fv fnUniformMatrix2fv;
    gl21PUniformMatrix3fv fnUniformMatrix3fv;
    gl21PUniformMatrix4fv fnUniformMatrix4fv;
    gl21PUniformMatrix2x3fv fnUniformMatrix2x3fv;
    gl21PUniformMatrix3x2fv fnUniformMatrix3x2fv;
    gl21PUniformMatrix2x4fv fnUniformMatrix2x4fv;
    gl21PUniformMatrix4x2fv fnUniformMatrix4x2fv;
    gl21PUniformMatrix3x4fv fnUniformMatrix3x4fv;
    gl21PUniformMatrix4x3fv fnUniformMatrix4x3fv;
    gl21PColorTable fnColorTable;
    gl21PColorTableParameterfv fnColorTableParameterfv;
    gl21PColorTableParameteriv fnColorTableParameteriv;
    gl21PColorSubTable fnColorSubTable;
    gl21PConvolutionFilter1D fnConvolutionFilter1D;
    gl21PConvolutionFilter2D fnConvolutionFilter2D;
    gl21PConvolutionParameterf fnConvolutionParameterf;
    gl21PConvolutionParameteri fnConvolutionParameteri;
    gl21PCopyColorTable fnCopyColorTable;
    gl21PCopyColorSubTable fnCopyColorSubTable;
    gl21PCopyConvolutionFilter1D fnCopyConvolutionFilter1D;
    gl21PCopyConvolutionFilter2D fnCopyConvolutionFilter2D;
    gl21PGetColorTable fnGetColorTable;
    gl21PGetColorTableParameterfv fnGetColorTableParameterfv;
    gl21PGetColorTableParameteriv fnGetColorTableParameteriv;
    gl21PGetConvolutionFilter fnGetConvolutionFilter;
    gl21PGetHistogram fnGetHistogram;
    gl21PGetHistogramParameterfv fnGetHistogramParameterfv;
    gl21PGetHistogramParameteriv fnGetHistogramParameteriv;
    gl21PGetSeparableFilter fnGetSeparableFilter;
    gl21PHistogram fnHistogram;
    gl21PMinmax fnMinmax;
    gl21PMultiTexCoord1s fnMultiTexCoord1s;
    gl21PMultiTexCoord1i fnMultiTexCoord1i;
    gl21PMultiTexCoord1f fnMultiTexCoord1f;
    gl21PMultiTexCoord1d fnMultiTexCoord1d;
    gl21PMultiTexCoord2s fnMultiTexCoord2s;
    gl21PMultiTexCoord2i fnMultiTexCoord2i;
    gl21PMultiTexCoord2f fnMultiTexCoord2f;
    gl21PMultiTexCoord2d fnMultiTexCoord2d;
    gl21PMultiTexCoord3s fnMultiTexCoord3s;
    gl21PMultiTexCoord3i fnMultiTexCoord3i;
    gl21PMultiTexCoord3f fnMultiTexCoord3f;
    gl21PMultiTexCoord3d fnMultiTexCoord3d;
    gl21PMultiTexCoord4s fnMultiTexCoord4s;
    gl21PMultiTexCoord4i fnMultiTexCoord4i;
    gl21PMultiTexCoord4f fnMultiTexCoord4f;
    gl21PMultiTexCoord4d fnMultiTexCoord4d;
    gl21PMultiTexCoord1sv fnMultiTexCoord1sv;
    gl21PMultiTexCoord1iv fnMultiTexCoord1iv;
    gl21PMultiTexCoord1fv fnMultiTexCoord1fv;
    gl21PMultiTexCoord1dv fnMultiTexCoord1dv;
    gl21PMultiTexCoord2sv fnMultiTexCoord2sv;
    gl21PMultiTexCoord2iv fnMultiTexCoord2iv;
    gl21PMultiTexCoord2fv fnMultiTexCoord2fv;
    gl21PMultiTexCoord2dv fnMultiTexCoord2dv;
    gl21PMultiTexCoord3sv fnMultiTexCoord3sv;
    gl21PMultiTexCoord3iv fnMultiTexCoord3iv;
    gl21PMultiTexCoord3fv fnMultiTexCoord3fv;
    gl21PMultiTexCoord3dv fnMultiTexCoord3dv;
    gl21PMultiTexCoord4sv fnMultiTexCoord4sv;
    gl21PMultiTexCoord4iv fnMultiTexCoord4iv;
    gl21PMultiTexCoord4fv fnMultiTexCoord4fv;
    gl21PMultiTexCoord4dv fnMultiTexCoord4dv;
    gl21PResetHistogram fnResetHistogram;
    gl21PResetMinmax fnResetMinmax;
    gl21PSeparableFilter2D fnSeparableFilter2D;
    gl21PBlendColor fnBlendColor;
    gl21PBlendEquation fnBlendEquation;
    gl21PCopyTexSubImage3D fnCopyTexSubImage3D;
    gl21PDrawRangeElements fnDrawRangeElements;
    gl21PTexImage3D fnTexImage3D;
    gl21PTexSubImage3D fnTexSubImage3D;
    gl21PActiveTexture fnActiveTexture;
    gl21PClientActiveTexture fnClientActiveTexture;
    gl21PCompressedTexImage1D fnCompressedTexImage1D;
    gl21PCompressedTexImage2D fnCompressedTexImage2D;
    gl21PCompressedTexImage3D fnCompressedTexImage3D;
    gl21PCompressedTexSubImage1D fnCompressedTexSubImage1D;
    gl21PCompressedTexSubImage2D fnCompressedTexSubImage2D;
    gl21PCompressedTexSubImage3D fnCompressedTexSubImage3D;
    gl21PGetCompressedTexImage fnGetCompressedTexImage;
    gl21PLoadTransposeMatrixd fnLoadTransposeMatrixd;
    gl21PLoadTransposeMatrixf fnLoadTransposeMatrixf;
    gl21PMultTransposeMatrixd fnMultTransposeMatrixd;
    gl21PMultTransposeMatrixf fnMultTransposeMatrixf;
    gl21PSampleCoverage fnSampleCoverage;
    gl21PBlendFuncSeparate fnBlendFuncSeparate;
    gl21PFogCoordPointer fnFogCoordPointer;
    gl21PFogCoordd fnFogCoordd;
    gl21PFogCoordf fnFogCoordf;
    gl21PFogCoorddv fnFogCoorddv;
    gl21PFogCoordfv fnFogCoordfv;
    gl21PMultiDrawArrays fnMultiDrawArrays;
    gl21PMultiDrawElements fnMultiDrawElements;
    gl21PPointParameterf fnPointParameterf;
    gl21PPointParameteri fnPointParameteri;
    gl21PSecondaryColor3b fnSecondaryColor3b;
    gl21PSecondaryColor3s fnSecondaryColor3s;
    gl21PSecondaryColor3i fnSecondaryColor3i;
    gl21PSecondaryColor3f fnSecondaryColor3f;
    gl21PSecondaryColor3d fnSecondaryColor3d;
    gl21PSecondaryColor3ub fnSecondaryColor3ub;
    gl21PSecondaryColor3us fnSecondaryColor3us;
    gl21PSecondaryColor3ui fnSecondaryColor3ui;
    gl21PSecondaryColor3bv fnSecondaryColor3bv;
    gl21PSecondaryColor3sv fnSecondaryColor3sv;
    gl21PSecondaryColor3iv fnSecondaryColor3iv;
    gl21PSecondaryColor3fv fnSecondaryColor3fv;
    gl21PSecondaryColor3dv fnSecondaryColor3dv;
    gl21PSecondaryColor3ubv fnSecondaryColor3ubv;
    gl21PSecondaryColor3usv fnSecondaryColor3usv;
    gl21PSecondaryColor3uiv fnSecondaryColor3uiv;
    gl21PSecondaryColorPointer fnSecondaryColorPointer;
    gl21PWindowPos2s fnWindowPos2s;
    gl21PWindowPos2i fnWindowPos2i;
    gl21PWindowPos2f fnWindowPos2f;
    gl21PWindowPos2d fnWindowPos2d;
    gl21PWindowPos3s fnWindowPos3s;
    gl21PWindowPos3i fnWindowPos3i;
    gl21PWindowPos3f fnWindowPos3f;
    gl21PWindowPos3d fnWindowPos3d;
    gl21PWindowPos2sv fnWindowPos2sv;
    gl21PWindowPos2iv fnWindowPos2iv;
    gl21PWindowPos2fv fnWindowPos2fv;
    gl21PWindowPos2dv fnWindowPos2dv;
    gl21PWindowPos3sv fnWindowPos3sv;
    gl21PWindowPos3iv fnWindowPos3iv;
    gl21PWindowPos3fv fnWindowPos3fv;
    gl21PWindowPos3dv fnWindowPos3dv;
    gl21PBeginQuery fnBeginQuery;
    gl21PBindBuffer fnBindBuffer;
    gl21PBufferData fnBufferData;
    gl21PBufferSubData fnBufferSubData;
    gl21PDeleteBuffers fnDeleteBuffers;
    gl21PDeleteQueries fnDeleteQueries;
    gl21PGenBuffers fnGenBuffers;
    gl21PGenQueries fnGenQueries;
    gl21PGetBufferParameteriv fnGetBufferParameteriv;
    gl21PGetBufferPointerv fnGetBufferPointerv;
    gl21PGetBufferSubData fnGetBufferSubData;
    gl21PGetQueryObjectiv fnGetQueryObjectiv;
    gl21PGetQueryObjectuiv fnGetQueryObjectuiv;
    gl21PGetQueryiv fnGetQueryiv;
    gl21PIsBuffer fnIsBuffer;
    gl21PIsQuery fnIsQuery;
    gl21PMapBuffer fnMapBuffer;
    gl21PUnmapBuffer fnUnmapBuffer;
    gl21PAttachShader fnAttachShader;
    gl21PBindAttribLocation fnBindAttribLocation;
    gl21PBlendEquationSeperate fnBlendEquationSeperate;
    gl21PCompileShader fnCompileShader;
    gl21PCreateProgram fnCreateProgram;
    gl21PCreateShader fnCreateShader;
    gl21PDeleteProgram fnDeleteProgram;
    gl21PDeleteShader fnDeleteShader;
    gl21PDetachShader fnDetachShader;
    gl21PEnableVertexAttribArray fnEnableVertexAttribArray;
    gl21PDisableVertexAttribArray fnDisableVertexAttribArray;
} gl21Context;

extern gl21Context* gl21NewContext();
void gl21Accum(gl21Context* glc, GLenum op, GLfloat value);
void gl21AlphaFunc(gl21Context* glc, GLenum func, GLclampf ref);
void gl21Begin(gl21Context* glc, GLenum mode);
void gl21End(gl21Context* glc);
void gl21Bitmap(gl21Context* glc, GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, GLubyte* bitmap);
void gl21BlendFunc(gl21Context* glc, GLenum sfactor, GLenum dfactor);
void gl21CallList(gl21Context* glc, GLuint list);
void gl21CallLists(gl21Context* glc, GLsizei n, GLenum type, GLvoid* lists);
void gl21Clear(gl21Context* glc, GLbitfield mask);
void gl21ClearAccum(gl21Context* glc, GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void gl21ClearColor(gl21Context* glc, GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha);
void gl21ClearDepth(gl21Context* glc, GLclampd depth);
void gl21ClearIndex(gl21Context* glc, GLfloat c);
void gl21ClearStencil(gl21Context* glc, GLint s);
void gl21ClipPlane(gl21Context* glc, GLenum plane, GLdouble* equation);
void gl21Color3b(gl21Context* glc, GLbyte red, GLbyte green, GLbyte blue);
void gl21Color3d(gl21Context* glc, GLdouble red, GLdouble green, GLdouble blue);
void gl21Color3f(gl21Context* glc, GLfloat red, GLfloat green, GLfloat blue);
void gl21Color3i(gl21Context* glc, GLint red, GLint green, GLint blue);
void gl21Color3s(gl21Context* glc, GLshort red, GLshort green, GLshort blue);
void gl21Color3ub(gl21Context* glc, GLubyte red, GLubyte green, GLubyte blue);
void gl21Color3ui(gl21Context* glc, GLuint red, GLuint green, GLuint blue);
void gl21Color3us(gl21Context* glc, GLushort red, GLushort green, GLushort blue);
void gl21Color4b(gl21Context* glc, GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha);
void gl21Color4d(gl21Context* glc, GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha);
void gl21Color4f(gl21Context* glc, GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void gl21Color4i(gl21Context* glc, GLint red, GLint green, GLint blue, GLint alpha);
void gl21Color4s(gl21Context* glc, GLshort red, GLshort green, GLshort blue, GLshort alpha);
void gl21Color4ub(gl21Context* glc, GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha);
void gl21Color4ui(gl21Context* glc, GLuint red, GLuint green, GLuint blue, GLuint alpha);
void gl21Color4us(gl21Context* glc, GLushort red, GLushort green, GLushort blue, GLushort alpha);
void gl21Color3bv(gl21Context* glc, GLbyte* v);
void gl21Color3dv(gl21Context* glc, GLdouble* v);
void gl21Color3fv(gl21Context* glc, GLfloat* v);
void gl21Color3iv(gl21Context* glc, GLint* v);
void gl21Color3sv(gl21Context* glc, GLshort* v);
void gl21Color3ubv(gl21Context* glc, GLubyte* v);
void gl21Color3uiv(gl21Context* glc, GLuint* v);
void gl21Color3usv(gl21Context* glc, GLushort* v);
void gl21Color4bv(gl21Context* glc, GLbyte* v);
void gl21Color4dv(gl21Context* glc, GLdouble* v);
void gl21Color4fv(gl21Context* glc, GLfloat* v);
void gl21Color4iv(gl21Context* glc, GLint* v);
void gl21Color4sv(gl21Context* glc, GLshort* v);
void gl21Color4ubv(gl21Context* glc, GLubyte* v);
void gl21Color4uiv(gl21Context* glc, GLuint* v);
void gl21Color4usv(gl21Context* glc, GLushort* v);
void gl21ColorMask(gl21Context* glc, GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
void gl21ColorMaterial(gl21Context* glc, GLenum face, GLenum mode);
void gl21CopyPixels(gl21Context* glc, GLint x, GLint y, GLsizei width, GLsizei height, GLenum type);
void gl21CullFace(gl21Context* glc, GLenum mode);
void gl21DeleteLists(gl21Context* glc, GLuint list, GLsizei range);
void gl21DepthFunc(gl21Context* glc, GLenum func);
void gl21DepthMask(gl21Context* glc, GLboolean flag);
void gl21DepthRange(gl21Context* glc, GLclampd zNear, GLclampd zFar);
void gl21Enable(gl21Context* glc, GLenum cap);
void gl21Disable(gl21Context* glc, GLenum cap);
void gl21DrawBuffer(gl21Context* glc, GLenum mode);
void gl21DrawPixels(gl21Context* glc, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid* data);
void gl21EdgeFlag(gl21Context* glc, GLboolean flag);
void gl21EdgeFlagv(gl21Context* glc, GLboolean* flag);
void gl21EdgeFlagPointer(gl21Context* glc, GLsizei stride, GLvoid* pointer);
void gl21EvalCoord1d(gl21Context* glc, GLdouble u);
void gl21EvalCoord1f(gl21Context* glc, GLfloat u);
void gl21EvalCoord2d(gl21Context* glc, GLdouble u, GLdouble v);
void gl21EvalCoord2f(gl21Context* glc, GLfloat u, GLfloat v);
void gl21EvalCoord1dv(gl21Context* glc, GLdouble* u);
void gl21EvalCoord1fv(gl21Context* glc, GLfloat* u);
void gl21EvalCoord2dv(gl21Context* glc, GLdouble* u);
void gl21EvalCoord2fv(gl21Context* glc, GLfloat* u);
void gl21EvalMesh1(gl21Context* glc, GLenum mode, GLint i1, GLint i2);
void gl21EvalMesh2(gl21Context* glc, GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2);
void gl21EvalPoint1(gl21Context* glc, GLint i);
void gl21EvalPoint2(gl21Context* glc, GLint i, GLint j);
void gl21FeedbackBuffer(gl21Context* glc, GLsizei size, GLenum type, GLfloat* buffer);
void gl21Finish(gl21Context* glc);
void gl21Flush(gl21Context* glc);
void gl21Fogf(gl21Context* glc, GLenum pname, GLfloat param);
void gl21Fogi(gl21Context* glc, GLenum pname, GLint param);
void gl21Fogfv(gl21Context* glc, GLenum pname, GLfloat* params);
void gl21Fogiv(gl21Context* glc, GLenum pname, GLint* params);
void gl21FrontFace(gl21Context* glc, GLenum mode);
void gl21Frustum(gl21Context* glc, GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
GLuint gl21GenLists(gl21Context* glc, GLsizei range);
void gl21GetBooleanv(gl21Context* glc, GLenum pname, GLboolean* params);
void gl21GetDoublev(gl21Context* glc, GLenum pname, GLdouble* params);
void gl21GetFloatv(gl21Context* glc, GLenum pname, GLfloat* params);
void gl21GetIntegerv(gl21Context* glc, GLenum pname, GLint* params);
void gl21GetClipPlane(gl21Context* glc, GLenum plane, GLdouble* equation);
GLenum gl21GetError(gl21Context* glc);
void gl21GetLightfv(gl21Context* glc, GLenum light, GLenum pname, GLfloat* params);
void gl21GetLightiv(gl21Context* glc, GLenum light, GLenum pname, GLint* params);
void gl21GetMapdv(gl21Context* glc, GLenum target, GLenum query, GLdouble* v);
void gl21GetMapfv(gl21Context* glc, GLenum target, GLenum query, GLfloat* v);
void gl21GetMapiv(gl21Context* glc, GLenum target, GLenum query, GLint* v);
void gl21GetMaterialfv(gl21Context* glc, GLenum face, GLenum pname, GLfloat* params);
void gl21GetMaterialiv(gl21Context* glc, GLenum face, GLenum pname, GLint* params);
void gl21GetPixelMapfv(gl21Context* glc, GLenum map, GLfloat* values);
void gl21GetPixelMapuiv(gl21Context* glc, GLenum map, GLuint* values);
void gl21GetPixelMapusv(gl21Context* glc, GLenum map, GLushort* values);
void gl21GetPolygonStipple(gl21Context* glc, GLubyte* pattern);
GLubyte* gl21GetString(gl21Context* glc, GLenum name);
void gl21GetTexEnvfv(gl21Context* glc, GLenum target, GLenum pname, GLfloat* params);
void gl21GetTexEnviv(gl21Context* glc, GLenum target, GLenum pname, GLint* params);
void gl21GetTexGendv(gl21Context* glc, GLenum coord, GLenum pname, GLdouble* params);
void gl21GetTexGenfv(gl21Context* glc, GLenum coord, GLenum pname, GLfloat* params);
void gl21GetTexGeniv(gl21Context* glc, GLenum coord, GLenum pname, GLint* params);
void gl21GetTexImage(gl21Context* glc, GLenum target, GLint level, GLenum format, GLenum type, GLvoid* pixels);
void gl21GetTexLevelParameterfv(gl21Context* glc, GLenum target, GLint level, GLenum pname, GLfloat* params);
void gl21GetTexLevelParameteriv(gl21Context* glc, GLenum target, GLint level, GLenum pname, GLint* params);
void gl21GetTexParameterfv(gl21Context* glc, GLenum target, GLenum pname, GLfloat* params);
void gl21GetTexParameteriv(gl21Context* glc, GLenum target, GLenum pname, GLint* params);
void gl21Hint(gl21Context* glc, GLenum target, GLenum mode);
void gl21Indexd(gl21Context* glc, GLdouble c);
void gl21Indexf(gl21Context* glc, GLfloat c);
void gl21Indexi(gl21Context* glc, GLint c);
void gl21Indexs(gl21Context* glc, GLshort c);
void gl21Indexdv(gl21Context* glc, GLdouble* c);
void gl21Indexfv(gl21Context* glc, GLfloat* c);
void gl21Indexiv(gl21Context* glc, GLint* c);
void gl21Indexsv(gl21Context* glc, GLshort* c);
void gl21IndexMask(gl21Context* glc, GLuint mask);
void gl21IndexPointer(gl21Context* glc, GLenum type, GLsizei stride, GLvoid* pointer);
void gl21InitNames(gl21Context* glc);
void gl21IsEnabled(gl21Context* glc, GLenum cap);
GLboolean gl21IsList(gl21Context* glc, GLuint list);
void gl21Lightf(gl21Context* glc, GLenum light, GLenum pname, GLfloat param);
void gl21Lighti(gl21Context* glc, GLenum light, GLenum pname, GLint param);
void gl21Lightfv(gl21Context* glc, GLenum light, GLenum pname, GLfloat* params);
void gl21Lightiv(gl21Context* glc, GLenum light, GLenum pname, GLint* params);
void gl21LightModelf(gl21Context* glc, GLenum pname, GLfloat param);
void gl21LightModeli(gl21Context* glc, GLenum pname, GLint param);
void gl21LightModelfv(gl21Context* glc, GLenum pname, GLfloat* params);
void gl21LightModeliv(gl21Context* glc, GLenum pname, GLint* params);
void gl21LineStipple(gl21Context* glc, GLint factor, GLushort pattern);
void gl21LineWidth(gl21Context* glc, GLfloat width);
void gl21ListBase(gl21Context* glc, GLuint base);
void gl21LoadIdentity(gl21Context* glc);
void gl21LoadMatrixd(gl21Context* glc, GLdouble* m);
void gl21LoadMatrixf(gl21Context* glc, GLfloat* m);
void gl21LoadName(gl21Context* glc, GLuint name);
void gl21LogicOp(gl21Context* glc, GLenum opcode);
void gl21Map1d(gl21Context* glc, GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, GLdouble* points);
void gl21Map1f(gl21Context* glc, GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, GLfloat* points);
void gl21Map2d(gl21Context* glc, GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, GLdouble* points);
void gl21Map2f(gl21Context* glc, GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, GLfloat* points);
void gl21MapGrid1d(gl21Context* glc, GLint un, GLdouble u1, GLdouble u2);
void gl21MapGrid1f(gl21Context* glc, GLint un, GLfloat u1, GLfloat u2);
void gl21MapGrid2d(gl21Context* glc, GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2);
void gl21MapGrid2f(gl21Context* glc, GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2);
void gl21Materialf(gl21Context* glc, GLenum face, GLenum pname, GLfloat param);
void gl21Materiali(gl21Context* glc, GLenum face, GLenum pname, GLint param);
void gl21Materialfv(gl21Context* glc, GLenum face, GLenum pname, GLfloat* params);
void gl21Materialiv(gl21Context* glc, GLenum face, GLenum pname, GLint* params);
void gl21MatrixMode(gl21Context* glc, GLenum mode);
void gl21MultMatrixd(gl21Context* glc, GLdouble* m);
void gl21MultMatrixf(gl21Context* glc, GLfloat* m);
void gl21NewList(gl21Context* glc, GLuint list, GLenum mode);
void gl21EndList(gl21Context* glc);
void gl21Normal3b(gl21Context* glc, GLbyte nx, GLbyte ny, GLbyte nz);
void gl21Normal3d(gl21Context* glc, GLdouble nx, GLdouble ny, GLdouble nz);
void gl21Normal3f(gl21Context* glc, GLfloat nx, GLfloat ny, GLfloat nz);
void gl21Normal3i(gl21Context* glc, GLint nx, GLint ny, GLint nz);
void gl21Normal3s(gl21Context* glc, GLshort nx, GLshort ny, GLshort nz);
void gl21Normal3bv(gl21Context* glc, GLbyte* v);
void gl21Normal3dv(gl21Context* glc, GLdouble* v);
void gl21Normal3fv(gl21Context* glc, GLfloat* v);
void gl21Normal3iv(gl21Context* glc, GLint* v);
void gl21Normal3sv(gl21Context* glc, GLshort* v);
void gl21Ortho(gl21Context* glc, GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zfar);
void gl21PassThrough(gl21Context* glc, GLfloat token);
void gl21PixelMapfv(gl21Context* glc, GLenum map, GLsizei mapsize, GLfloat* values);
void gl21PixelMapuiv(gl21Context* glc, GLenum map, GLsizei mapsize, GLuint* values);
void gl21PixelMapusv(gl21Context* glc, GLenum map, GLsizei mapsize, GLushort* values);
void gl21PixelStoref(gl21Context* glc, GLenum pname, GLfloat param);
void gl21PixelStorei(gl21Context* glc, GLenum pname, GLint param);
void gl21PixelTransferf(gl21Context* glc, GLenum pname, GLfloat param);
void gl21PixelTransferi(gl21Context* glc, GLenum pname, GLint param);
void gl21PixelZoom(gl21Context* glc, GLfloat xfactor, GLfloat yfactor);
void gl21PointSize(gl21Context* glc, GLfloat size);
void gl21PolygonMode(gl21Context* glc, GLenum face, GLenum mode);
void gl21PolygonStipple(gl21Context* glc, GLubyte* mask);
void gl21PushAttrib(gl21Context* glc, GLbitfield mask);
void gl21PopAttrib(gl21Context* glc);
void gl21PushMatrix(gl21Context* glc);
void gl21PopMatrix(gl21Context* glc);
void gl21PushName(gl21Context* glc, GLuint name);
void gl21PopName(gl21Context* glc);
void gl21RasterPos2d(gl21Context* glc, GLdouble x, GLdouble y);
void gl21RasterPos2f(gl21Context* glc, GLfloat x, GLfloat y);
void gl21RasterPos2i(gl21Context* glc, GLint x, GLint y);
void gl21RasterPos2s(gl21Context* glc, GLshort x, GLshort y);
void gl21RasterPos3d(gl21Context* glc, GLdouble x, GLdouble y, GLdouble z);
void gl21RasterPos3f(gl21Context* glc, GLfloat x, GLfloat y, GLfloat z);
void gl21RasterPos3i(gl21Context* glc, GLint x, GLint y, GLint z);
void gl21RasterPos3s(gl21Context* glc, GLshort x, GLshort y, GLshort z);
void gl21RasterPos4d(gl21Context* glc, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
void gl21RasterPos4f(gl21Context* glc, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
void gl21RasterPos4i(gl21Context* glc, GLint x, GLint y, GLint z, GLint w);
void gl21RasterPos4s(gl21Context* glc, GLshort x, GLshort y, GLshort z, GLshort w);
void gl21RasterPos2dv(gl21Context* glc, GLdouble* v);
void gl21RasterPos2fv(gl21Context* glc, GLfloat* v);
void gl21RasterPos2iv(gl21Context* glc, GLint* v);
void gl21RasterPos2sv(gl21Context* glc, GLshort* v);
void gl21RasterPos3dv(gl21Context* glc, GLdouble* v);
void gl21RasterPos3fv(gl21Context* glc, GLfloat* v);
void gl21RasterPos3iv(gl21Context* glc, GLint* v);
void gl21RasterPos3sv(gl21Context* glc, GLshort* v);
void gl21RasterPos4dv(gl21Context* glc, GLdouble* v);
void gl21RasterPos4fv(gl21Context* glc, GLfloat* v);
void gl21RasterPos4iv(gl21Context* glc, GLint* v);
void gl21RasterPos4sv(gl21Context* glc, GLshort* v);
void gl21ReadBuffer(gl21Context* glc, GLenum mode);
void gl21ReadPixels(gl21Context* glc, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid* pixels);
void gl21Rectd(gl21Context* glc, GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2);
void gl21Rectf(gl21Context* glc, GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2);
void gl21Recti(gl21Context* glc, GLint x1, GLint y1, GLint x2, GLint y2);
void gl21Rects(gl21Context* glc, GLshort x1, GLshort y1, GLshort x2, GLshort y2);
void gl21Rectdv(gl21Context* glc, GLdouble* v1, GLdouble* v2);
void gl21Rectfv(gl21Context* glc, GLfloat* v1, GLfloat* v2);
void gl21Rectiv(gl21Context* glc, GLint* v1, GLint* v2);
void gl21Rectsv(gl21Context* glc, GLshort* v1, GLshort* v2);
GLint gl21RenderMode(gl21Context* glc, GLenum mode);
void gl21Rotated(gl21Context* glc, GLdouble angle, GLdouble x, GLdouble y, GLdouble z);
void gl21Rotatef(gl21Context* glc, GLfloat angle, GLfloat x, GLfloat y, GLfloat z);
void gl21Scaled(gl21Context* glc, GLdouble x, GLdouble y, GLdouble z);
void gl21Scalef(gl21Context* glc, GLfloat x, GLfloat y, GLfloat z);
void gl21Scissor(gl21Context* glc, GLint x, GLint y, GLsizei width, GLsizei height);
void gl21SelectBuffer(gl21Context* glc, GLsizei size, GLuint* buffer);
void gl21ShadeModel(gl21Context* glc, GLenum mode);
void gl21StencilFunc(gl21Context* glc, GLenum func, GLint ref, GLuint mask);
void gl21StencilMask(gl21Context* glc, GLuint mask);
void gl21StencilOp(gl21Context* glc, GLenum fail, GLenum zfail, GLenum zpass);
void gl21TexCoord1d(gl21Context* glc, GLdouble s);
void gl21TexCoord1f(gl21Context* glc, GLfloat s);
void gl21TexCoord1i(gl21Context* glc, GLint s);
void gl21TexCoord1s(gl21Context* glc, GLshort s);
void gl21TexCoord2d(gl21Context* glc, GLdouble s, GLdouble t);
void gl21TexCoord2f(gl21Context* glc, GLfloat s, GLfloat t);
void gl21TexCoord2i(gl21Context* glc, GLint s, GLint t);
void gl21TexCoord2s(gl21Context* glc, GLshort s, GLshort t);
void gl21TexCoord3d(gl21Context* glc, GLdouble s, GLdouble t, GLdouble r);
void gl21TexCoord3f(gl21Context* glc, GLfloat s, GLfloat t, GLfloat r);
void gl21TexCoord3i(gl21Context* glc, GLint s, GLint t, GLint r);
void gl21TexCoord3s(gl21Context* glc, GLshort s, GLshort t, GLshort r);
void gl21TexCoord4d(gl21Context* glc, GLdouble s, GLdouble t, GLdouble r, GLdouble q);
void gl21TexCoord4f(gl21Context* glc, GLfloat s, GLfloat t, GLfloat r, GLfloat q);
void gl21TexCoord4i(gl21Context* glc, GLint s, GLint t, GLint r, GLint q);
void gl21TexCoord4s(gl21Context* glc, GLshort s, GLshort t, GLshort r, GLshort q);
void gl21TexCoord1dv(gl21Context* glc, GLdouble* v);
void gl21TexCoord1fv(gl21Context* glc, GLfloat* v);
void gl21TexCoord1iv(gl21Context* glc, GLint* v);
void gl21TexCoord1sv(gl21Context* glc, GLshort* v);
void gl21TexCoord2dv(gl21Context* glc, GLdouble* v);
void gl21TexCoord2fv(gl21Context* glc, GLfloat* v);
void gl21TexCoord2iv(gl21Context* glc, GLint* v);
void gl21TexCoord2sv(gl21Context* glc, GLshort* v);
void gl21TexCoord3dv(gl21Context* glc, GLdouble* v);
void gl21TexCoord3fv(gl21Context* glc, GLfloat* v);
void gl21TexCoord3iv(gl21Context* glc, GLint* v);
void gl21TexCoord3sv(gl21Context* glc, GLshort* v);
void gl21TexCoord4dv(gl21Context* glc, GLdouble* v);
void gl21TexCoord4fv(gl21Context* glc, GLfloat* v);
void gl21TexCoord4iv(gl21Context* glc, GLint* v);
void gl21TexCoord4sv(gl21Context* glc, GLshort* v);
void gl21TexEnvf(gl21Context* glc, GLenum target, GLenum pname, GLfloat param);
void gl21TexEnvi(gl21Context* glc, GLenum target, GLenum pname, GLint param);
void gl21TexEnvfv(gl21Context* glc, GLenum target, GLenum pname, GLfloat* params);
void gl21TexEnviv(gl21Context* glc, GLenum target, GLenum pname, GLint* params);
void gl21TexGend(gl21Context* glc, GLenum coord, GLenum pname, GLdouble param);
void gl21TexGenf(gl21Context* glc, GLenum coord, GLenum pname, GLfloat param);
void gl21TexGeni(gl21Context* glc, GLenum coord, GLenum pname, GLint param);
void gl21TexGendv(gl21Context* glc, GLenum coord, GLenum pname, GLdouble* params);
void gl21TexGenfv(gl21Context* glc, GLenum coord, GLenum pname, GLfloat* params);
void gl21TexGeniv(gl21Context* glc, GLenum coord, GLenum pname, GLint* params);
void gl21TexImage1D(gl21Context* glc, GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, GLvoid* pixels);
void gl21TexImage2D(gl21Context* glc, GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, GLvoid* pixels);
void gl21TexParameterf(gl21Context* glc, GLenum target, GLenum pname, GLfloat param);
void gl21TexParameteri(gl21Context* glc, GLenum target, GLenum pname, GLint param);
void gl21TexParameterfv(gl21Context* glc, GLenum target, GLenum pname, GLfloat* params);
void gl21TexParameteriv(gl21Context* glc, GLenum target, GLenum pname, GLint* params);
void gl21Translated(gl21Context* glc, GLdouble x, GLdouble y, GLdouble z);
void gl21Translatef(gl21Context* glc, GLfloat x, GLfloat y, GLfloat z);
void gl21Vertex2s(gl21Context* glc, GLshort x, GLshort y);
void gl21Vertex2i(gl21Context* glc, GLint x, GLint y);
void gl21Vertex2f(gl21Context* glc, GLfloat x, GLfloat y);
void gl21Vertex2d(gl21Context* glc, GLdouble x, GLdouble y);
void gl21Vertex3s(gl21Context* glc, GLshort x, GLshort y, GLshort z);
void gl21Vertex3i(gl21Context* glc, GLint x, GLint y, GLint z);
void gl21Vertex3f(gl21Context* glc, GLfloat x, GLfloat y, GLfloat z);
void gl21Vertex3d(gl21Context* glc, GLdouble x, GLdouble y, GLdouble z);
void gl21Vertex4s(gl21Context* glc, GLshort x, GLshort y, GLshort z, GLshort w);
void gl21Vertex4i(gl21Context* glc, GLint x, GLint y, GLint z, GLint w);
void gl21Vertex4f(gl21Context* glc, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
void gl21Vertex4d(gl21Context* glc, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
void gl21Viewport(gl21Context* glc, GLint x, GLint y, GLsizei width, GLsizei height);
void gl21GetConvolutionParameterfv(gl21Context* glc, GLenum target, GLenum pname, GLfloat* params);
void gl21GetConvolutionParameteriv(gl21Context* glc, GLenum target, GLenum pname, GLint* params);
GLboolean gl21AreTexturesResident(gl21Context* glc, GLsizei n, GLuint* textures, GLboolean* residences);
void gl21ArrayElement(gl21Context* glc, GLint i);
void gl21DrawArrays(gl21Context* glc, GLenum mode, GLint first, GLsizei count);
void gl21DrawElements(gl21Context* glc, GLenum mode, GLsizei count, GLenum type, GLvoid* indices);
void gl21GetPointerv(gl21Context* glc, GLenum pname, GLvoid* params);
void gl21PolygonOffset(gl21Context* glc, GLfloat factor, GLfloat units);
void gl21CopyTexImage1D(gl21Context* glc, GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLint border);
void gl21CopyTexImage2D(gl21Context* glc, GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
void gl21CopyTexSubImage1D(gl21Context* glc, GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width);
void gl21CopyTexSubImage2D(gl21Context* glc, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
void gl21BindTexture(gl21Context* glc, GLenum target, GLuint texture);
void gl21DeleteTextures(gl21Context* glc, GLsizei n, GLuint* textures);
void gl21GenTextures(gl21Context* glc, GLsizei n, GLuint* textures);
GLboolean gl21IsTexture(gl21Context* glc, GLuint texture);
void gl21ColorPointer(gl21Context* glc, GLint size, GLenum type, GLsizei stride, GLvoid* pointer);
void gl21EnableClientState(gl21Context* glc, GLenum cap);
void gl21DisableClientState(gl21Context* glc, GLenum cap);
void gl21Indexub(gl21Context* glc, GLubyte c);
void gl21Indexubv(gl21Context* glc, GLubyte* c);
void gl21InterleavedArrays(gl21Context* glc, GLenum format, GLsizei stride, GLvoid* pointer);
void gl21NormalPointer(gl21Context* glc, GLenum type, GLsizei stride, GLvoid* pointer);
void gl21PushClientAttrib(gl21Context* glc, GLbitfield mask);
void gl21PrioritizeTextures(gl21Context* glc, GLsizei n, GLuint* textures, GLclampf* priorities);
void gl21PopClientAttrib(gl21Context* glc);
void gl21TexCoordPointer(gl21Context* glc, GLint size, GLenum type, GLsizei stride, GLvoid* pointer);
void gl21TexSubImage1D(gl21Context* glc, GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, GLvoid* pixels);
void gl21TexSubImage2D(gl21Context* glc, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid* pixels);
void gl21VertexPointer(gl21Context* glc, GLint size, GLenum type, GLsizei stride, GLvoid* pointer);
void gl21DrawBuffers(gl21Context* glc, GLsizei n, GLenum* bufs);
void gl21GetActiveAttrib(gl21Context* glc, GLuint program, GLuint index, GLsizei bufSize, GLsizei* length, GLint* size, GLenum* type, GLchar* name);
void gl21GetActiveUniform(gl21Context* glc, GLuint program, GLuint index, GLsizei bufSize, GLsizei* length, GLint* size, GLenum* type, GLchar* name);
void gl21GetAttachedShaders(gl21Context* glc, GLuint program, GLsizei maxCount, GLsizei* count, GLuint* shaders);
GLint gl21GetAttribLocation(gl21Context* glc, GLuint program, GLchar* name);
void gl21GetProgramiv(gl21Context* glc, GLuint program, GLenum pname, GLint* params);
void gl21GetProgramInfoLog(gl21Context* glc, GLuint program, GLsizei maxLength, GLsizei* length, GLchar* infoLog);
void gl21GetShaderiv(gl21Context* glc, GLuint program, GLenum pname, GLint* params);
void gl21GetShaderInfoLog(gl21Context* glc, GLuint shader, GLsizei maxLength, GLsizei* length, GLchar* infoLog);
void gl21GetShaderSource(gl21Context* glc, GLuint shader, GLsizei bufSize, GLsizei* length, GLchar* source);
void gl21GetUniformfv(gl21Context* glc, GLuint program, GLint location, GLfloat* params);
void gl21GetUniformiv(gl21Context* glc, GLuint program, GLint location, GLint* params);
GLint gl21GetUniformLocation(gl21Context* glc, GLuint program, GLchar* name);
void gl21GetVertexAttribdv(gl21Context* glc, GLuint index, GLenum pname, GLdouble* params);
void gl21GetVertexAttribfv(gl21Context* glc, GLuint index, GLenum pname, GLfloat* params);
void gl21GetVertexAttribiv(gl21Context* glc, GLuint index, GLenum pname, GLint* params);
void gl21GetVertexAttribPointerv(gl21Context* glc, GLuint index, GLenum pname, GLvoid* pointer);
GLboolean gl21IsProgram(gl21Context* glc, GLuint program);
GLboolean gl21IsShader(gl21Context* glc, GLuint shader);
void gl21LinkProgram(gl21Context* glc, GLuint program);
void gl21ShaderSource(gl21Context* glc, GLuint shader, GLsizei count, GLchar** string, GLint* length);
void gl21StencilFuncSeparate(gl21Context* glc, GLenum face, GLenum func, GLint ref, GLuint mask);
void gl21StencilMaskSeparate(gl21Context* glc, GLenum face, GLuint mask);
void gl21StencilOpSeparate(gl21Context* glc, GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass);
void gl21Uniform1f(gl21Context* glc, GLint location, GLfloat v0);
void gl21Uniform2f(gl21Context* glc, GLint location, GLfloat v0, GLfloat v1);
void gl21Uniform3f(gl21Context* glc, GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
void gl21Uniform4f(gl21Context* glc, GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
void gl21Uniform1i(gl21Context* glc, GLint location, GLint v0);
void gl21Uniform2i(gl21Context* glc, GLint location, GLint v0, GLint v1);
void gl21Uniform3i(gl21Context* glc, GLint location, GLint v0, GLint v1, GLint v2);
void gl21Uniform4i(gl21Context* glc, GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
void gl21Uniform1fv(gl21Context* glc, GLint location, GLsizei count, GLfloat* value);
void gl21Uniform2fv(gl21Context* glc, GLint location, GLsizei count, GLfloat* value);
void gl21Uniform3fv(gl21Context* glc, GLint location, GLsizei count, GLfloat* value);
void gl21Uniform4fv(gl21Context* glc, GLint location, GLsizei count, GLfloat* value);
void gl21Uniform1iv(gl21Context* glc, GLint location, GLsizei count, GLint* value);
void gl21Uniform2iv(gl21Context* glc, GLint location, GLsizei count, GLint* value);
void gl21Uniform3iv(gl21Context* glc, GLint location, GLsizei count, GLint* value);
void gl21Uniform4iv(gl21Context* glc, GLint location, GLsizei count, GLint* value);
void gl21UseProgram(gl21Context* glc, GLuint program);
void gl21ValidateProgram(gl21Context* glc, GLuint program);
void gl21VertexAttribPointer(gl21Context* glc, GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, GLvoid* pointer);
void gl21VertexAttrib1f(gl21Context* glc, GLuint index, GLfloat v0);
void gl21VertexAttrib1s(gl21Context* glc, GLuint index, GLshort v0);
void gl21VertexAttrib1d(gl21Context* glc, GLuint index, GLdouble v0);
void gl21VertexAttrib2f(gl21Context* glc, GLuint index, GLfloat v0, GLfloat v1);
void gl21VertexAttrib2s(gl21Context* glc, GLuint index, GLshort v0, GLshort v1);
void gl21VertexAttrib2d(gl21Context* glc, GLuint index, GLdouble v0, GLdouble v1);
void gl21VertexAttrib3f(gl21Context* glc, GLuint index, GLfloat v0, GLfloat v1, GLfloat v2);
void gl21VertexAttrib3s(gl21Context* glc, GLuint index, GLshort v0, GLshort v1, GLshort v2);
void gl21VertexAttrib3d(gl21Context* glc, GLuint index, GLdouble v0, GLdouble v1, GLdouble v2);
void gl21VertexAttrib4f(gl21Context* glc, GLuint index, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
void gl21VertexAttrib4s(gl21Context* glc, GLuint index, GLshort v0, GLshort v1, GLshort v2, GLshort v3);
void gl21VertexAttrib4d(gl21Context* glc, GLuint index, GLdouble v0, GLdouble v1, GLdouble v2, GLdouble v3);
void gl21VertexAttrib4Nuv(gl21Context* glc, GLuint index, GLubyte v0, GLubyte v1, GLubyte v2, GLubyte v3);
void gl21VertexAttrib1fv(gl21Context* glc, GLuint index, GLfloat* v);
void gl21VertexAttrib1sv(gl21Context* glc, GLuint index, GLshort* v);
void gl21VertexAttrib1dv(gl21Context* glc, GLuint index, GLdouble* v);
void gl21VertexAttrib2fv(gl21Context* glc, GLuint index, GLfloat* v);
void gl21VertexAttrib2sv(gl21Context* glc, GLuint index, GLshort* v);
void gl21VertexAttrib2dv(gl21Context* glc, GLuint index, GLdouble* v);
void gl21VertexAttrib3fv(gl21Context* glc, GLuint index, GLfloat* v);
void gl21VertexAttrib3sv(gl21Context* glc, GLuint index, GLshort* v);
void gl21VertexAttrib3dv(gl21Context* glc, GLuint index, GLdouble* v);
void gl21VertexAttrib4fv(gl21Context* glc, GLuint index, GLfloat* v);
void gl21VertexAttrib4sv(gl21Context* glc, GLuint index, GLshort* v);
void gl21VertexAttrib4dv(gl21Context* glc, GLuint index, GLdouble* v);
void gl21VertexAttrib4iv(gl21Context* glc, GLuint index, GLint* v);
void gl21VertexAttrib4bv(gl21Context* glc, GLuint index, GLbyte* v);
void gl21VertexAttrib4ubv(gl21Context* glc, GLuint index, GLubyte* v);
void gl21VertexAttrib4usv(gl21Context* glc, GLuint index, GLushort* v);
void gl21VertexAttrib4uiv(gl21Context* glc, GLuint index, GLuint* v);
void gl21VertexAttrib4Nbv(gl21Context* glc, GLuint index, GLbyte* v);
void gl21VertexAttrib4Nsv(gl21Context* glc, GLuint index, GLshort* v);
void gl21VertexAttrib4Niv(gl21Context* glc, GLuint index, GLint* v);
void gl21VertexAttrib4Nubv(gl21Context* glc, GLuint index, GLubyte* v);
void gl21VertexAttrib4Nusv(gl21Context* glc, GLuint index, GLushort* v);
void gl21VertexAttrib4Nuiv(gl21Context* glc, GLuint index, GLuint* v);
void gl21UniformMatrix2fv(gl21Context* glc, GLint location, GLsizei count, GLboolean transpose, GLfloat* value);
void gl21UniformMatrix3fv(gl21Context* glc, GLint location, GLsizei count, GLboolean transpose, GLfloat* value);
void gl21UniformMatrix4fv(gl21Context* glc, GLint location, GLsizei count, GLboolean transpose, GLfloat* value);
void gl21UniformMatrix2x3fv(gl21Context* glc, GLint location, GLsizei count, GLboolean transpose, GLfloat* value);
void gl21UniformMatrix3x2fv(gl21Context* glc, GLint location, GLsizei count, GLboolean transpose, GLfloat* value);
void gl21UniformMatrix2x4fv(gl21Context* glc, GLint location, GLsizei count, GLboolean transpose, GLfloat* value);
void gl21UniformMatrix4x2fv(gl21Context* glc, GLint location, GLsizei count, GLboolean transpose, GLfloat* value);
void gl21UniformMatrix3x4fv(gl21Context* glc, GLint location, GLsizei count, GLboolean transpose, GLfloat* value);
void gl21UniformMatrix4x3fv(gl21Context* glc, GLint location, GLsizei count, GLboolean transpose, GLfloat* value);
void gl21ColorTable(gl21Context* glc, GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, GLvoid* data);
void gl21ColorTableParameterfv(gl21Context* glc, GLenum target, GLenum pname, GLfloat* params);
void gl21ColorTableParameteriv(gl21Context* glc, GLenum target, GLenum pname, GLint* params);
void gl21ColorSubTable(gl21Context* glc, GLenum target, GLsizei start, GLsizei count, GLenum format, GLenum type, GLvoid* data);
void gl21ConvolutionFilter1D(gl21Context* glc, GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, GLvoid* data);
void gl21ConvolutionFilter2D(gl21Context* glc, GLenum target, GLenum internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid* data);
void gl21ConvolutionParameterf(gl21Context* glc, GLenum target, GLenum pname, GLfloat params);
void gl21ConvolutionParameteri(gl21Context* glc, GLenum target, GLenum pname, GLint params);
void gl21CopyColorTable(gl21Context* glc, GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width);
void gl21CopyColorSubTable(gl21Context* glc, GLenum target, GLsizei start, GLint x, GLint y, GLsizei width);
void gl21CopyConvolutionFilter1D(gl21Context* glc, GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width);
void gl21CopyConvolutionFilter2D(gl21Context* glc, GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height);
void gl21GetColorTable(gl21Context* glc, GLenum target, GLenum format, GLenum type, GLvoid* table);
void gl21GetColorTableParameterfv(gl21Context* glc, GLenum target, GLenum pname, GLfloat* params);
void gl21GetColorTableParameteriv(gl21Context* glc, GLenum target, GLenum pname, GLint* params);
void gl21GetConvolutionFilter(gl21Context* glc, GLenum target, GLenum format, GLenum type, GLvoid* image);
void gl21GetHistogram(gl21Context* glc, GLenum target, GLboolean reset, GLenum format, GLenum type, GLvoid* values);
void gl21GetHistogramParameterfv(gl21Context* glc, GLenum target, GLenum pname, GLfloat* params);
void gl21GetHistogramParameteriv(gl21Context* glc, GLenum target, GLenum pname, GLint* params);
void gl21GetSeparableFilter(gl21Context* glc, GLenum target, GLenum format, GLenum type, GLvoid* row, GLvoid* column, GLvoid* span);
void gl21Histogram(gl21Context* glc, GLenum target, GLsizei width, GLenum internalformat, GLboolean sink);
void gl21Minmax(gl21Context* glc, GLenum target, GLenum internalformat, GLboolean sink);
void gl21MultiTexCoord1s(gl21Context* glc, GLenum target, GLshort s);
void gl21MultiTexCoord1i(gl21Context* glc, GLenum target, GLint s);
void gl21MultiTexCoord1f(gl21Context* glc, GLenum target, GLfloat s);
void gl21MultiTexCoord1d(gl21Context* glc, GLenum target, GLdouble s);
void gl21MultiTexCoord2s(gl21Context* glc, GLenum target, GLshort s, GLshort t);
void gl21MultiTexCoord2i(gl21Context* glc, GLenum target, GLint s, GLint t);
void gl21MultiTexCoord2f(gl21Context* glc, GLenum target, GLfloat s, GLfloat t);
void gl21MultiTexCoord2d(gl21Context* glc, GLenum target, GLdouble s, GLdouble t);
void gl21MultiTexCoord3s(gl21Context* glc, GLenum target, GLshort s, GLshort t, GLshort r);
void gl21MultiTexCoord3i(gl21Context* glc, GLenum target, GLint s, GLint t, GLint r);
void gl21MultiTexCoord3f(gl21Context* glc, GLenum target, GLfloat s, GLfloat t, GLfloat r);
void gl21MultiTexCoord3d(gl21Context* glc, GLenum target, GLdouble s, GLdouble t, GLdouble r);
void gl21MultiTexCoord4s(gl21Context* glc, GLenum target, GLshort s, GLshort t, GLshort r, GLshort q);
void gl21MultiTexCoord4i(gl21Context* glc, GLenum target, GLint s, GLint t, GLint r, GLint q);
void gl21MultiTexCoord4f(gl21Context* glc, GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q);
void gl21MultiTexCoord4d(gl21Context* glc, GLenum target, GLdouble s, GLdouble t, GLdouble r, GLdouble q);
void gl21MultiTexCoord1sv(gl21Context* glc, GLenum target, GLshort* v);
void gl21MultiTexCoord1iv(gl21Context* glc, GLenum target, GLint* v);
void gl21MultiTexCoord1fv(gl21Context* glc, GLenum target, GLfloat* v);
void gl21MultiTexCoord1dv(gl21Context* glc, GLenum target, GLdouble* v);
void gl21MultiTexCoord2sv(gl21Context* glc, GLenum target, GLshort* v);
void gl21MultiTexCoord2iv(gl21Context* glc, GLenum target, GLint* v);
void gl21MultiTexCoord2fv(gl21Context* glc, GLenum target, GLfloat* v);
void gl21MultiTexCoord2dv(gl21Context* glc, GLenum target, GLdouble* v);
void gl21MultiTexCoord3sv(gl21Context* glc, GLenum target, GLshort* v);
void gl21MultiTexCoord3iv(gl21Context* glc, GLenum target, GLint* v);
void gl21MultiTexCoord3fv(gl21Context* glc, GLenum target, GLfloat* v);
void gl21MultiTexCoord3dv(gl21Context* glc, GLenum target, GLdouble* v);
void gl21MultiTexCoord4sv(gl21Context* glc, GLenum target, GLshort* v);
void gl21MultiTexCoord4iv(gl21Context* glc, GLenum target, GLint* v);
void gl21MultiTexCoord4fv(gl21Context* glc, GLenum target, GLfloat* v);
void gl21MultiTexCoord4dv(gl21Context* glc, GLenum target, GLdouble* v);
void gl21ResetHistogram(gl21Context* glc, GLenum target);
void gl21ResetMinmax(gl21Context* glc, GLenum target);
void gl21SeparableFilter2D(gl21Context* glc, GLenum target, GLenum internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid* row, GLvoid* column);
void gl21BlendColor(gl21Context* glc, GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha);
void gl21BlendEquation(gl21Context* glc, GLenum mode);
void gl21CopyTexSubImage3D(gl21Context* glc, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height);
void gl21DrawRangeElements(gl21Context* glc, GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, GLvoid* indices);
void gl21TexImage3D(gl21Context* glc, GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, GLvoid* pixels);
void gl21TexSubImage3D(gl21Context* glc, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLvoid* pixels);
void gl21ActiveTexture(gl21Context* glc, GLenum texture);
void gl21ClientActiveTexture(gl21Context* glc, GLenum texture);
void gl21CompressedTexImage1D(gl21Context* glc, GLenum target, GLint level, GLenum internalformat, GLsizei width, GLint border, GLsizei imageSize, GLvoid* data);
void gl21CompressedTexImage2D(gl21Context* glc, GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, GLvoid* data);
void gl21CompressedTexImage3D(gl21Context* glc, GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, GLvoid* data);
void gl21CompressedTexSubImage1D(gl21Context* glc, GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, GLvoid* data);
void gl21CompressedTexSubImage2D(gl21Context* glc, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, GLvoid* data);
void gl21CompressedTexSubImage3D(gl21Context* glc, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, GLvoid* data);
void gl21GetCompressedTexImage(gl21Context* glc, GLenum target, GLint lod, GLvoid* img);
void gl21LoadTransposeMatrixd(gl21Context* glc, GLdouble* m);
void gl21LoadTransposeMatrixf(gl21Context* glc, GLdouble* m);
void gl21MultTransposeMatrixd(gl21Context* glc, GLdouble* m);
void gl21MultTransposeMatrixf(gl21Context* glc, GLfloat* m);
void gl21SampleCoverage(gl21Context* glc, GLclampf value, GLboolean invert);
void gl21BlendFuncSeparate(gl21Context* glc, GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha);
void gl21FogCoordPointer(gl21Context* glc, GLenum type, GLsizei stride, GLvoid* pointer);
void gl21FogCoordd(gl21Context* glc, GLdouble coord);
void gl21FogCoordf(gl21Context* glc, GLfloat coord);
void gl21FogCoorddv(gl21Context* glc, GLdouble* coord);
void gl21FogCoordfv(gl21Context* glc, GLfloat* coord);
void gl21MultiDrawArrays(gl21Context* glc, GLenum mode, GLint* first, GLsizei* count, GLsizei primcount);
void gl21MultiDrawElements(gl21Context* glc, GLenum mode, GLsizei* count, GLenum type, GLvoid* indices, GLsizei primcount);
void gl21PointParameterf(gl21Context* glc, GLenum pname, GLfloat param);
void gl21PointParameteri(gl21Context* glc, GLenum pname, GLint param);
void gl21SecondaryColor3b(gl21Context* glc, GLbyte red, GLbyte green, GLbyte blue);
void gl21SecondaryColor3s(gl21Context* glc, GLshort red, GLshort green, GLshort blue);
void gl21SecondaryColor3i(gl21Context* glc, GLint red, GLint green, GLint blue);
void gl21SecondaryColor3f(gl21Context* glc, GLfloat red, GLfloat green, GLfloat blue);
void gl21SecondaryColor3d(gl21Context* glc, GLdouble red, GLdouble green, GLdouble blue);
void gl21SecondaryColor3ub(gl21Context* glc, GLubyte red, GLubyte green, GLubyte blue);
void gl21SecondaryColor3us(gl21Context* glc, GLushort red, GLushort green, GLushort blue);
void gl21SecondaryColor3ui(gl21Context* glc, GLuint red, GLuint green, GLuint blue);
void gl21SecondaryColor3bv(gl21Context* glc, GLbyte* v);
void gl21SecondaryColor3sv(gl21Context* glc, GLshort* v);
void gl21SecondaryColor3iv(gl21Context* glc, GLint* v);
void gl21SecondaryColor3fv(gl21Context* glc, GLfloat* v);
void gl21SecondaryColor3dv(gl21Context* glc, GLdouble* v);
void gl21SecondaryColor3ubv(gl21Context* glc, GLubyte* v);
void gl21SecondaryColor3usv(gl21Context* glc, GLushort* v);
void gl21SecondaryColor3uiv(gl21Context* glc, GLuint* v);
void gl21SecondaryColorPointer(gl21Context* glc, GLint size, GLenum type, GLsizei stride, GLvoid* pointer);
void gl21WindowPos2s(gl21Context* glc, GLshort x, GLshort y);
void gl21WindowPos2i(gl21Context* glc, GLint x, GLint y);
void gl21WindowPos2f(gl21Context* glc, GLfloat x, GLfloat y);
void gl21WindowPos2d(gl21Context* glc, GLdouble x, GLdouble y);
void gl21WindowPos3s(gl21Context* glc, GLshort x, GLshort y, GLshort z);
void gl21WindowPos3i(gl21Context* glc, GLint x, GLint y, GLint z);
void gl21WindowPos3f(gl21Context* glc, GLfloat x, GLfloat y, GLfloat z);
void gl21WindowPos3d(gl21Context* glc, GLdouble x, GLdouble y, GLdouble z);
void gl21WindowPos2sv(gl21Context* glc, GLshort* v);
void gl21WindowPos2iv(gl21Context* glc, GLint* v);
void gl21WindowPos2fv(gl21Context* glc, GLfloat* v);
void gl21WindowPos2dv(gl21Context* glc, GLdouble* v);
void gl21WindowPos3sv(gl21Context* glc, GLshort* v);
void gl21WindowPos3iv(gl21Context* glc, GLint* v);
void gl21WindowPos3fv(gl21Context* glc, GLfloat* v);
void gl21WindowPos3dv(gl21Context* glc, GLdouble* v);
void gl21BeginQuery(gl21Context* glc, GLenum target, GLuint id);
void gl21BindBuffer(gl21Context* glc, GLenum target, GLuint buffer);
void gl21BufferData(gl21Context* glc, GLenum target, GLsizeiptr size, GLvoid* data, GLenum usage);
void gl21BufferSubData(gl21Context* glc, GLenum target, GLenum offset, GLsizeiptr size, GLvoid* data);
void gl21DeleteBuffers(gl21Context* glc, GLsizei n, GLuint* buffers);
void gl21DeleteQueries(gl21Context* glc, GLsizei n, GLuint* ids);
void gl21GenBuffers(gl21Context* glc, GLsizei n, GLuint* buffers);
void gl21GenQueries(gl21Context* glc, GLsizei n, GLuint* ids);
void gl21GetBufferParameteriv(gl21Context* glc, GLenum target, GLenum value, GLint* data);
void gl21GetBufferPointerv(gl21Context* glc, GLenum target, GLenum pname, GLvoid* params);
void gl21GetBufferSubData(gl21Context* glc, GLenum target, GLintptr offset, GLsizeiptr size, GLvoid* data);
void gl21GetQueryObjectiv(gl21Context* glc, GLuint id, GLenum pname, GLint* params);
void gl21GetQueryObjectuiv(gl21Context* glc, GLuint id, GLenum pname, GLuint* params);
void gl21GetQueryiv(gl21Context* glc, GLenum target, GLenum pname, GLint* params);
GLboolean gl21IsBuffer(gl21Context* glc, GLuint buffer);
GLboolean gl21IsQuery(gl21Context* glc, GLuint id);
GLvoid* gl21MapBuffer(gl21Context* glc, GLenum target, GLenum access);
GLboolean gl21UnmapBuffer(gl21Context* glc, GLenum target);
void gl21AttachShader(gl21Context* glc, GLuint program, GLuint shader);
void gl21BindAttribLocation(gl21Context* glc, GLuint program, GLuint index, GLchar* name);
void gl21BlendEquationSeperate(gl21Context* glc, GLenum modeRGB, GLenum modeAlpha);
void gl21CompileShader(gl21Context* glc, GLuint shader);
GLuint gl21CreateProgram(gl21Context* glc);
GLuint gl21CreateShader(gl21Context* glc, GLenum shaderType);
void gl21DeleteProgram(gl21Context* glc, GLuint program);
void gl21DeleteShader(gl21Context* glc, GLuint shader);
void gl21DetachShader(gl21Context* glc, GLuint program, GLuint shader);
void gl21EnableVertexAttribArray(gl21Context* glc, GLuint index);
void gl21DisableVertexAttribArray(gl21Context* glc, GLuint index);
